### ISSUE TITLE
quickcheck generators for shelley updates

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#1034]
The updates in the shelley exec model are defined here: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/src/Updates.hs#L87

Write quickcheck generators for this data type.

**Comment by JaredCorduan** [comment]
thanks to @uroboros for letting me know that this issue is redundant with #875. I will close #875 and mention here that it may make sense to have this generator as a part of the LEDGER STS Trace generator.

**Comment by mgajda** [comment]
So I am generating this little baby here.
![Data contained in Update](https://user-images.githubusercontent.com/685529/69188868-9df11100-0b1d-11ea-9f2e-4406eb71ce05.png)
