### ISSUE TITLE
Diagnose STS transition failure with QuickCheck Delegation generators / properties

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-specs#1039]
[This patch](https://github.com/input-output-hk/cardano-ledger-specs/files/3886642/break_STS.patch.txt) can be applied to `master` (as of `8d6478ac`) with something like `cat ~/Downloads/break_STS.patch.txt | git am`.  Running `cabal v2-test delegation-test` should yield

```
    STS Rules - Pool Properties
      newly registered stake pool is added to appropriate state mappings:                     OK (45.10s)
          ✓ newly registered stake pool is added to appropriate state mappings passed 300 tests.
      retired stake pool is removed from appropriate state mappings and marked  for retiring: FAIL
        *** Failed! (after 1 test):
        Exception while generating shrink-list:
          applySTSIndifferently was called with an empty set of rules
          CallStack (from HasCallStack):
            error, called at src/Control/State/Transition.hs:178:17 in small-steps-0.1.0.0-inplace:Control.State.Transition
        Exception thrown while showing test case:
          applySTSIndifferently was called with an empty set of rules
          CallStack (from HasCallStack):
            error, called at src/Control/State/Transition.hs:178:17 in small-steps-0.1.0.0-inplace:Control.State.Transition

        Use --quickcheck-replay=882481 to reproduce.
```

- It's unclear to me why this occurs. If someone can look into this issue it would be great, so that I can jump over to the byron/consensus integration task.
- The current approach (on `master`) works around this issue by generating & shrinking `SourceSignalTarget POOL`. However as @uroboros pointed out, there are issues with shrinking a `[SourceSignalTarget sts]` because any shrunk signal can cause all subsequent sources & targets to become invalid (i.e. they will not match the resultant STS state obtained by applying the shrunk signal).
  - The approach in this patch doesn't have the issue of shrinking which the `SourceSignalTarget` gen/shrink approach has because of https://github.com/input-output-hk/cardano-ledger-specs/blob/cbf9bc9c730020adfa32e537ead3a426bbafd7d7/byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs#L126 use of `Trace.closure`, we should rebuild a `Trace` with internal consistency & validity.
  - One advantage of gen/shrinking `SourceSignalTarget` is that it's smaller and easier to read in a test-suite failure printout.
  - To address the unwieldiness of the full `Trace sts` we could extend `Control.State.Transition.Trace.Generator.QuickCheck.forAllTrace` to `forAllTraceShow` with an `(Trace sts -> String)` custom show function. This would resemble `forAllShrinkShow` from QuickCheck. The function could transform the Trace to `SourceSignalTarget POOL` and `show` it to ease the diagnosis of bad signals.

**Comment by mhuesch** [comment]
This patch is formatted using `git format-patch`, so `cat`ing it into `git am` should work. 

[break_STS.patch.txt](https://github.com/input-output-hk/cardano-ledger-specs/files/3878070/break_STS.patch.txt)

**Comment by uroboros** [comment]
@mhuesch sure I'll pick this up
