### ISSUE TITLE
Specifying and limiting script execution resources

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1047]
Do we want to limit the maximum resources scripts are allowed to use? Do we want to do this per script, per block, or per transaction? Or all three?

A closely related issue: do we want a transaction to *specify* the resources it is expected to use for script computation per-script or should it be per-transaction

My first thought was "yes, we definitely should limit them in one of those ways at least".
If a transaction submits a super resource-heavy script that *does* validate, but fails to validate in some other way, the whole block is thrown away and fees never collected (even if the script was already run). We might want to avoid that. But the rule where the scripts are actually run is the bottom rule in the sense that there isnt anything below it in the dependancy graph, so this shouldn't matter too much. 

But it still probably is a good idea to have a limit.

**Comment by polinavino** [comment]
My vote is to limit resources per script:

Limiting script execution per script allows for straightforward parallel validation of multiple scripts at a time as it does not require passing the correct currently variable of "remaining for-fee Ada" to each validator (instead, we pass the originally allocated fee or `exunits` amount for that specific script). This also looks much nicer as STS ledger rules and is much more in line with how UTxO updating works currently. 

Also, adding a per-script fee (or `exunits`) value to an input is not excessively memory-heavy and not a big change to the transaction format.

**Comment by polinavino** [comment]
Without a specific value for `remaining_fees`, we cannot apply the script validator directly in the ledger rules, because we need this value as one of the inputs to the validator. Thus, a "per transaction" fee will mean that we have a base case that actually updates the ledger and fees, and a rule that says something like : 

- process the first script in the list, if it validates, subtract however much it cost to validate it from the total `remaining_fees` value, which would initially be `txfee tx`,
- then, apply the same rule to the rest of the list, with a different `remaining_fees` value, which is now `remaining_fees - script cost`

**Comment by michaelpj** [comment]
I think there are two independent issues here (TBH I think they should have different issues):
1. Should there be a "maximum script resources" parameter in the protocol parameters that puts an upper limit on *any* script execution? How should it be scoped (per script, per tx, per block)
2. How should we record the execution limits that the *user* has put on their scripts (in the form of the fees they have provided to cover execution)?

I think @dcoutts convinced us that we should do 1. on the basis of some participation argument which maybe he can clarify in text. I also think he suggested that it should be per block. I don't have a strong opinion on that.

----

As for 2:

I am sympathetic to the argument that having explicit per-input fees makes it easier to do parallel evaluation. I think that's true, although I don't think it's *that* hard to do parallel evaluation even with an aggregate fee. (I've sketched out a way we could do it below.)

However, I don't buy that having a single aggregate fee would complicate the rules. In particular, I think the following would work as a ledger rule:

> The sum of the execution costs of all the scripts must be less than the fee remaining after the initial phase of validation.

As a *declarative* specification this is fine. A naive *implementation* of this might run all the scripts and only check whether they were over at the end - which vulnerable to the kind of attacks we don't want. But we're perfectly at liberty to write a less-naive implementation that runs one script at a time and terminates early if it runs out of money - this is a perfectly acceptable proof that the declarative rule does not hold.

Even if we did want to specify the "chained" script execution in the ledger rules, we shouldn't need multiple rules, we could just us a fold. Here in Haskell:
```haskell
-- | Given a script and the current gas, computes whether the script validates
--  (returning 'False' if we ran out of gas) and the remaining gas.
runScript :: Script -> Gas -> (Bool, Gas)

scriptsValid :: Gas -> [Script] -> (Bool, Gas)
scriptsValid initialGas scripts = foldl runOne (false, initialGas) scripts
  where
    runOne (validSoFar, remainingGas) script =
      if !validSoFar 
      then (False, remainingGas) 
      else runScript script remainingGas
```

---

Doing script evaluation in parallel with `N` threads:
- Divide up the gas between the threads.
- Queue all the scripts, have an allocator assign them to available threads.
- If a thread runs out of gas without finishing a job, kill the thread, suspend the job, and put it back on the queue.
- Either we finish all our jobs or we run out of live threads, in which case we didn't have enough gas.

This is pretty naive, but should involve some bounded number of task switches and very little locking.

**Comment by polinavino** [comment]
Yeah, we could do it this way. Then the list of scripts in 
`scriptsValid :: Gas -> [Script] -> (Bool, Gas)`

should be a list of the full triplet (Validator, Data, Redeemer), which would have to be prepared separately before calling `scriptsValid`. I still prefer per-script but I wont insist.

**Comment by polinavino** [comment]
If we decide to go the *per-transaction* route, it sounds like we are doing the keeping track of remaining gas/fees in the ledger rules. 

For this, we want to know specifically what the total `exunits`/Ada is that is allocated just for script validation. Otherwise, we can try to infer this from the txfee minus the minfee (or somehow based on fee-marked inputs). I think an explicit total for script fees makes more sense.

**Comment by reactormonk** [comment]
Purely from the UX side, it'd be better if we don't lose a transaction because one script got too much mana (or ex, or gas), which would have been enough if it'd been allocated to the script in need.

**Comment by michaelpj** [comment]
> For this, we want to know specifically what the total exunits/Ada is that is allocated just for script validation. Otherwise, we can try to infer this from the txfee minus the minfee (or somehow based on fee-marked inputs). I think an explicit total for script fees makes more sense.

I don't think it matters much. But if we're lumping all the fees together in aggregate... then we might as well lump together the script and non-script fees. Then subtracting the amount needed for the other bits of validation gives you the amount for script execution (just as subtracting the amount used for a script execution gives us the amount available for the subsequent ones).

> Otherwise, it is not clear what the surplus fee is. Or does this not matter?

I can't think of a reason why it would matter at the moment!

**Comment by michaelpj** [comment]
Polina commented on the other issue:

> I am now more convinced we should indeed have a per-transaction fee which includes all scripts and iterates over them as each one spends part of the fee. Mostly due to the issue of signing exunits, which would allow us to get rid of the need for that, as well as get rid of the problem of having exunits be indexed by different things for different purposes (utxo spending vs certificates vs reward withdrawals)

Per our discussion yesterday, I realised something:
- We need to include the *overall* fee in the body, since that affects the movement of funds.
- However, we could have per-script limits *as well* as an overall fee. These would then *not* need to be in the body, since the overall fee field is sufficient to determine the movement of funds.

Interestingly, this is also forwards-compatible: we can start out with an aggregate fee field, and then later add the per-script limits, since all they do is add additional constraints, without changing balancing.

**Comment by polinavino** [comment]
I'll make the per-transaction version today and see if everyone likes that better. It will indeed be more forward compatible than going the other direction
