### ISSUE TITLE
Coin, Value, and Quantity Usage

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1049]
- Do we want to have `Value` be both positive and negative quantity (no strictly positive version)?
- Do we want to have the administrative fields be `Coin` rather than `Value` (e.g. rewards, deposits, fees, etc)?
- Should we have two separate types: `Quantity` and `Coin`? 

If we keep administrative fields as Ada, I think they should be of type `Coin` rather than `Quantity`

**Comment by michaelpj** [comment]
> Do we want to have Value be both positive and negative quantity (no strictly positive version)?

IMO yes. It simplifies the types a bit, it's similar to how values in outputs work in the current spec, it's future-proof.

> Do we want to have the administrative fields be Coin rather than Value (e.g. rewards, deposits, fees, etc)?

I think they should be `Value` for more-or-less the same reason as above, but I don't mind terribly if it's `Coin`.

> Should we have two separate types: Quantity and Coin?

> If we keep administrative fields as Ada, I think they should be of type Coin rather than Quantity

`Coin` is a `Quantity` of Ada right? (We actually call our such type `Ada`, which I think is better than `Coin`!) You *could* merge them by having the Ada part be contextual, i.e. "a `Quantity` in this field means a quantity of Ada", but I think it's better to be clear.

**Comment by polinavino** [comment]
That all sounds good. `Coin` is what the ledger spec uses now, that is why I am using it.

**Comment by JaredCorduan** [comment]
for multi-currency, I was expecting to swap out all the `Coin`s for `Value`, and just add a few checks for the spots when only Ada are appropriate (the administrative fields). having an `Ada` type is fine too. but either way, `Coin` and `Quantity` are redundant.

**Comment by polinavino** [comment]
Are we totally sure now that we want to do everything in Value (and get rid of Coin entirely)? That means all the administrative fields, like reserves, fee pot, treasury, fees, rewards, etc? 

This means adding checks everywhere to make sure those fields only contain Ada, and staking calculations are still only in Ada.

**Comment by michaelpj** [comment]
I think so.

I don't think we need checks everywhere. We need checks in one place where we do basic transaction validity checking, and then we can do it all in one place and not worry about it elsewhere.

**Comment by polinavino** [comment]
Most recent consensus on the question of what the administrative fields such as fees, treasury, deposits, and reward calculations, in the ledger should be expressed in (i.e. `Value` , `Coin`, which is the integer wrapper for specifically Lovelace, or `Quantity`):
- using Ada for these things will never change, and it does not add anything to have these things be non-currency-specific. So, they will remain `Coin`

**Comment by polinavino** [comment]
^^
