### ISSUE TITLE
Evaluate QuickCheck for effects on CI time

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#105]
Hedgehog seems to be problematic with Travis CI in that tests require an order of magnitude more time than locally.

After this issue we
 - MUST be aware whether Quickcheck tests are also affected by this

**Comment by dnadales** [comment]
Quoting @mgudemann 

> I didn't run into this problem with QC, but it's not clear whether it was because of QC or some Travis VM instance issue before
