### ISSUE TITLE
The executable spec supporting both Plutus and no-Plutus ledger

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1051]
I guess we agreed this is a good idea?

**Comment by JaredCorduan** [comment]
if we want to release shelley without plutus, then yes, we need to keep them separate.

**Comment by polinavino** [comment]
I meant the executable spec which will have Plutus will have a parameter which can be toggled to allow it to operate the current Shelley-spec way, without Plutus.

**Comment by JaredCorduan** [comment]
I am hesitant to do that until Shelley is released.

**Comment by mgudemann** [comment]
I agree with Jared on this.

Would it be possible to have a parallel `Plutus` branch that includes Plutus functionality and routinely merges new functionality from `master` until after Shelley release when `Plutus` itself can be merged into `master`? I'd be happy to assist in any git merge conflict resolution.

**Comment by polinavino** [comment]
I would be good with that. and thank you for the offer, I will quite likely need the help.

**Comment by polinavino** [comment]
Parametrization of ledger types and rules over Era is now completed
