### ISSUE TITLE
Tagging inputs as "for fees"

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-ledger-specs#1053]
I'm confused about what we decided for this (the perils of having only meetings again!).

It looks like @polinavino has implemented the suggestion of tagging fee inputs. @dcoutts had a different suggestion, which was to have a simple-enough and generous-enough algorithm for picking which inputs are lost, something like "start with the smallest and (Ada-only?) input and work your way up".

I don't remember that we clearly decided on one or the other - or did we?

**Comment by michaelpj** [comment]
(I don't have permission to label this, perhaps someone else can.)

**Comment by JaredCorduan** [comment]
> (I don't have permission to label this, perhaps someone else can.)

I've just added you as a collaborator @michaelpj

**Comment by polinavino** [comment]
I think at a ledger discussion we ended up agreeing that labelling inputs gives people as much if not more privacy in the sense that one can opt to label all the inputs as "for fees" if they want to be as vague as possible about it with the associated risk. The algorithm deciding what ones are "for fees" *still* has the result that it is public knowledge what inputs will be used for fees

**Comment by reactormonk** [comment]
Some context: this is for when a transaction fails, that the fees can still be collected?

**Comment by michaelpj** [comment]
Simon: yes, since failing a transaction due to script costs might happen after the node has incurred some moderate costs running the scripts to that point, we want them to be compensated. So unlike with the other stages of validation ("stage 1"), if script validation fails ("stage 2") the failed transaction is recorded on the chain and the validating node takes "the fees".

The problem is working out what "the fees" are: in an extreme case, you might even be expecting to pay them out of the script output which failed to validate! The solution we've ended up at is that some set of inputs must be marked as fee inputs, and these must jointly cover the fee and be denominated purely in Ada. These are the inputs you lose if "stage 2" fails, the rest are just left alone.

**Comment by polinavino** [comment]
I am still not totally clear on the fee payment: we want to throw out any transaction that has any fee-marked inputs that contain non-Ada values, right? Or did we decide that we just want to ignore the non-Ada inputs that are marked for fees as if theyre not marked to pay fees (this seems like a bit of extra effort just to sort through fee inputs)?

**Comment by michaelpj** [comment]
I think we wanted to separate it into two things:
- Wherever we ask the question "how much is there in fees?" we add up all the Ada in all the fee-marked inputs (like what we do for staking).
- We add an independent validity condition that says "all fee-marked inputs only contain Ada".

I think  we could take the first point even further: it would be nice to have as many of the fee-related conditions as possible work in `Value`. For example, rather than checking:
```
sum (map adaValueOf inputs) >= adaValueof (fee)
```
(we decided to make the `fee` field be `Value` too, right?)
we could instead say
```
sum (map valueOf inputs) >= fee
```
Similarly, with the running total of the script execution cost usage, we can just check whether it's greater than the fees in `Value`, and then we don't need to talk about `Ada` at all, except in the side condition that says that the fee field (like the fee-marked inputs) must be in `Ada`.

**Comment by polinavino** [comment]
Fee is Coin, only non-script, non-MA inputs can be marked for-fees.
