### ISSUE TITLE
Do we need a third class of "segregated data"?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-ledger-specs#1054]
At the moment, we have witnesses that are separate from the transaction body. They are separate because they are not essential for reconstructing the UTXO set, only for validating the addition of transactions to the ledger, so we can omit them in some cases.

We have several other bits of ancillary data that we've added or are considering adding:
1. Validator scripts (as a map from hash to script)
2. Data values (as a map from hash to data)
3. Transaction metadata (as a map from not-hashes to something)

These have a few properties:
- Not needed for UTXO reconstruction: 1, 2, and 3. So they could all be "segregated".
- Self-validating: 1, 2 (since we can just check the hashes match, and it's fine to have as much in there as you like). This means 1 and 2 don't need to be signed, but 3 does, so it might have to be in the transaction body.

Annoyingly, the current segregated witnesses really need to have both of those properties, since they're outside the transaction body. So it's unclear what to do with e.g. metadata, which ideally it would be nice to be able to strip, but also have signed.

**Comment by JaredCorduan** [comment]
having the data values outside of the transaction body makes a lot of sense. It doesn't matter to me if it's a separate category from with validator scripts, etc.  wherever they end up, we do need to make sure that the data values are accounted for in the fee calculation.

**Comment by michaelpj** [comment]
I've realised that I was confused here: there is a clear distinction between what needs to go in the body and what doesn't, and we're not trying to ensure integrity of the transaction with our signatures, so we really do only have two classes of data.

Related: https://github.com/input-output-hk/cardano-ledger-specs/issues/1057#issuecomment-559430330
