### ISSUE TITLE
Write a specification for `Data`

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-ledger-specs#1067]
We'd like to use the Plutus `Data` type for e.g. the values of metadata items.

We'd therefore like to have a standalone specification of it. This probably needs:
- A formal description of the type, ideally using CDDL
- A specification of how to encode/decode it from CBOR (should be straightforward if we do https://github.com/input-output-hk/cardano-ledger-specs/issues/1066)

It could probably also do with a better name than `Data`!

**Comment by JaredCorduan** [comment]
@michaelpj - [This PR](https://github.com/input-output-hk/cardano-ledger-specs/pull/1289) adds the necessary documentation as an appendix to the Shelley design document. It's not standalone, but I think both the shelley ledger spec and the plutus docs could reference it.

**Comment by michaelpj** [comment]
That's okay for now, although it'll be a bit weird for us to be referring to the "metadata value" type from the Shelley spec...
