### ISSUE TITLE
Should the "forged" value stay as is in the preservation of value equation? 

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1068]
`forged tx` lives on the *consumed* side of the preservation of value equation. 
Roughly, the reasoning for this is that when tokens are added to the UTxO by a transaction, these new UTxO entries go on the "produced" side. If the value in these new entries is coming from forging new tokens, we must account for them by balancing this equation on the "consumed" side by adding the `forged tx` value there. 

That is, putting  `forged tx` on the consumed sided will mean that we do not need to flip the sign for forged. Like every other term in the sums on both sides of the preservation of value equation, forged will be *added*, and it seems natural to represent "creating tokens out of thin air" with a positive value of forged, and destroying them with a negative (rather than the other way around, or splitting it up into forged and destroyed). 

I think `forged` is fine as is in that equation.

**Comment by michaelpj** [comment]
I like the sign argument.
