### ISSUE TITLE
How to implement size restrictions on data in metadata (and Plutus data)?

### ISSUE THREAD

**Issue by michaelpj** [input-output-hk/cardano-ledger-specs#1069]
@dcoutts has said that we want to have size restrictions on transaction metadata (and also Plutus data values) in order to prevent people from putting copyright information in them.

I believe the current proposal is to have a size restriction on the *leaves* of the data: i.e. bytestring literals. This means that people can still split up their image into a list of bytestrings, but it's not there _simpliciter_.

----

However, this is awkward for usage with Plutus, because it introduces a discontinuity. Suppose that someone has a data value that (unwisely) contains a bytestring that grows as the contract continues. Suddenly, it crosses the size threshold! Now it is *impossible* to advance the contract.

This seems bad. Generally, discontinuities are bad because people can slowly get themselves into a situation, and then suddenly they can't extricate themselves. Even if advancing the contract is really valuable to you, you can't do it.

So here's an alternative suggestion: have an exponentially increasing cost for data. This means that if you really need 5 more bytes, then you can pay for 5 more bytes, but it would still be prohibitively expensive to put lots of images on the chain.

---

An additional consideration is that Plutus validator scripts themselves can contain bytestring literals. We should probably also apply the same restriction to those.

cc @mchakravarty

**Comment by JaredCorduan** [comment]
64 bytes is a nice sweet spot between being big enough for counters, but small enough to disallow things that we do not want. It's true that one could still write a sufficiently bad Plutus script that could run into the size limit. But I don't think that it is worth the extra complexity to accommodate for this.
