### ISSUE TITLE
Wallet and Blockchain explorer expectations for Plutus integration

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1079]
What are some of the things that will be expected from the wallet and the blockchain explorer for Plutus integration to be possible? I will take a look now at the Plutus repo to see what is already done there to start answering this question. 

I am looking for any input on this, especially with regards to further changes to the wallet and explorer due to the ledger functionality outlined in the Plutus integration doc.

**Comment by j-mueller** [comment]
The interactions that we're assuming our contracts are able to do are all under [`Plutus.Contract.Effects`](https://github.com/input-output-hk/plutus/tree/master/plutus-contract/src/Language/Plutus/Contract/Effects)

* AwaitSlot: Get a notification when a slot has been reached
* AwaitTxConfirmed: Get a notification when a transaction has been confirmed (ideally with different confirmation levels, for example when it's first added to the ledger, or when it is `k` blocks deep)
* ExposeEndpoint: Get some input from the user
* OwnPubKey: Get a public key that is considered part of the user's own funds
* UtxoAt: Get the unspent outputs at an address
* WatchAddress: Given an address, get the first transaction that spends or produces an output at the address
* WriteTx: Send an [`UnbalancedTx`](https://github.com/input-output-hk/plutus/blob/master/plutus-contract/src/Language/Plutus/Contract/Tx.hs#L66) to be balanced, signed and submitted to the network

**Comment by polinavino** [comment]
This is tracked elsewhere now (wallet-team Jira)
