### ISSUE TITLE
UTxO entry deposits

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1080]
This is not ready to be resolved immediately, but I believe is still an issue that is being considered:

Should there be a (decaying) deposit that must be paid when adding a new entry to the ledger UTxO? 

This was more relevant when potentially large data values were intended to be stored in full in the UTxO (rather than just their hashes).

**Comment by polinavino** [comment]
Deposits are really hard to refund, especially if a UTxO entry is a script address - who even gets the deposit back in that case? We'd have to keep track of who paid to the script, and it could be another script. 

This would be smoother if there was some way to collect the fee for keeping an entry in the UTxO directly from the amount in the entry itself, but not just at spending time (so that unspendable entries can still pay for living in the UTxO?)

**Comment by polinavino** [comment]
Some thoughts on deposits:

**Questions to answer:**
- Is there a deposit amount together with a deposit decay function `(d, f)`, such that the Ada collected by this scheme sustainably covers the costs the growing UTxO (including any accidentally unspendable entries doomed to haunt it forever), but is not prohibitively large, discouraging users from using the system

- If there is such a pair `(d, f)`, should the party making the UTxO entry be paying the deposit? 
downside: in this case, it is entirely unclear how and to who to refund it (with something like, adding a refund address to the UTxO entry)

or should it be the party consuming the UTxO entry that is forced to pay the decayed amount?
downside: the user with the agency to decide how many UTxO entries to create when paying someone, ie.
`txin |-> (a, 6)` vs `txin1 |-> (a, 2)` and `txin2 |-> (a, 2)` and `txin3 |-> (a, 2)` 
is not necessarily the same user that must be paying the decayed deposit amount when spending these outputs (and will have to pay more if the tokens are distributed over several outputs)

**Deposit alternatives:**
1. If a transaction has `x` inputs and `y` outputs, if `y>x`, the transaction must pay a fee for 
each of the `y-x` outputs 
- No questions about who is paying or getting a refund
- Discourages making dust entries
- Could be used for just non-Ada or Plutus script entries (which are bigger)
- Very similar to decaying deposits after the point in time where there is less than 1 Lovelace left in the decayed deposit calculation

2. Limited time entries: pay a fee per unit of time an entry will be allowed to exist in the UTxO 
- Would require an extra `SlotNo` field in these entries to indicate when this entry will be garbage-collected (Ada goes into some pot, other tokens are destroyed)
- Does not need to be a linear function
- Could be mandatory for, for ex. certain kinds of script outputs, which are more likely to be unspendable by accident
- Could be non-mandatory if combined with (1), i.e. a fee for making more entries than spending, and some of the new entries would require a smaller fee because they're limited-existence.

**Comment by michaelpj** [comment]
> in this case, it is entirely unclear how and to who to refund it (without something like, adding a refund address to the UTxO entry)

Dumb suggestion: what if it went to the reward account of the staking key? 

My reasoning here is that the staking key in a sense denotes the "beneficiary owner" of the output. This is the person who benefits from its stake... and perhaps it could also be the person who's "on the hook" for the deposit, and thus gets the refund when it happens.

More pragmatically: we already have a mechanism for attaching an account to an output, it would be neat to reuse it.

> If a transaction has x inputs and y outputs, if y>x, the transaction must pay a fee for
each of the y-x outputs

Do you get a refund if `x > y`?

> Limited time entries: pay a fee per unit of time an entry will be allowed to exist in the UTxO

I'm a bit scared of this. It adds a new and exciting way to lose all your money.

It would be slightly less bad if the money could at least go to somewhere sensible. My dumb suggestion would again be the reward account of the staking key (note that we'd need to allow non-Ada value in reward accounts... I told you the generality would be useful!).

**Comment by polinavino** [comment]
> Dumb suggestion: what if it went to the reward account of the staking key?

hmmmm... i like it - could be a great idea!! i dont see a problem with doing that immediately, but it might be ideologically wrong perhaps? in that, it's mixing account-style and UTxO style. But even if that is true (as it is anyways true for reward accounts), adding this particular use case still avoids the pitfalls of account style accounting i guess? 

> Do you get a refund if x > y?

No, where would this money come from? It would have to be a whole new scheme to make up if we want this to happen

> I'm a bit scared of this. It adds a new and exciting way to lose all your money.
...

Yeah! multi-purpose reward accounts! 
This would mean the reward account is the cheapest place to keep ones money, though. Make a very short-lived UTxO entry, and get it in your reward account on expiry. Since reward accounts are already paid for by deposits, too. So this could work? maybe?

The non-ada tokes I was picturing would be just destroyed ..

And more importantly, this scheme would be opt-in, for special cases where expect the UTxO entry will be consumed shortly, like if it's cheaper to make this limited-time output for the length of time of a Marlow contract time-out than pay a fee for infinite existence of the entry.

**Comment by michaelpj** [comment]
> i dont see a problem with doing that immediately, but it might be ideologically wrong perhaps? in that, it's mixing account-style and UTxO style. But even if that is true (as it is anyways true for reward accounts), adding this particular use case still avoids the pitfalls of account style accounting i guess?

Well, we *have* accounts for precisely this kind of thing, so I don't see it as any weirder than reward accounts.

> No, where would this money come from? It would have to be a whole new scheme to make up if we want this to happen

It would have to come out of whatever pot the deposits go into. But this is weird I agree.

> This would mean the reward account is the cheapest place to keep ones money, though. Make a very short-lived UTxO entry, and get it in your reward account on expiry. Since reward accounts are already paid for by deposits, too. So this could work? maybe?

Yikes, I hadn't thought about that. Awkward chimeric ledgers by the back-door. Perhaps that's bad. Not sure.

> The non-ada tokes I was picturing would be just destroyed ..

Why? Everything should work fine with `Value` as the *contents* of reward accounts. Repeat after me "Ada is just a special kind of token" :p

> And more importantly, this scheme would be opt-in, for special cases where expect the UTxO entry will be consumed shortly, like if it's cheaper to make this limited-time output for the length of time of a Marlow contract time-out than pay a fee for infinite existence of the entry.

I don't think we've resolved whether it's opt-in or not... It still adds an attack vector to scripts, since if someone locks some money up in some ironclad smart contract for you, but then it expires and the money goes to the staking account which happens to be theirs, you still get screwed.

**Comment by polinavino** [comment]
For MC, it might also make sense to have deposits be a function of the size of a UTxO entry, rather than a fixed deposit amount per entry

**Comment by polinavino** [comment]
To summarize the "pay more for taking up more UTxO space" proposal, suppose 

`realized_inputs` are the full UTxO entries corresponding to the inputs in a transaction
`realized_outputs` are the full UTxO entries corresponding formed out of the outputs of a tx
`extra_space = size (realized_outputs) - size (realized_inputs)`
`stake_utxo_space`  is the total UTxO size occupied by all the UTxO entries associated with a specific staking credential

The suggestion is
- inputs are free  (excluded from tx size calculation)
- outputs (excluded from tx size calculation)
- `extra_space` is expensive 
- at the time of reward calculation, for each staking credential, the reward amount is docked based on the `stake_utxo_space`, either proportionally or by subtracting `some_const*stake_utxo_space`. This docked amount is not redistributed to others

Why does this make sense?:
- consider this a "fee for UTxO space resource use expansion", not a deposit, as you do not get it back
- provides incentive not to grow the UTxO (charge extra for `extra_space`)
- provides incentive to consolidate entries (so reward is not docked)
- works for MC just as well as just Ada
- works for microtransactions and those requiring small change
- you are not paying a deposit for someone else's tokens, that *they* can have as payment. This needs to be the case for MC tokens. People wont want to pay another user to keep their token in the UTxO. 
- does not discourage adding multiple inputs, as they are free
- discourages "polluting" others' UTxOs with trivial entries, as this costs money (also, even if this docks their rewards, the polluter does not get more because of this)

Note that over the lifetime of the UTxO, this ends up looking very much like deposits, even without getting them back. Each transaction, there are two options:

1.  you have enough UTxOs (space-wise) in your wallet to add to the inputs to make `extra_space = 0`
In this case, you dont need to pay the extra space fee

2. you do not have UTxOs that consume enough space in you wallet, and you have to pay for some `extra_space`, i.e. taking up more space in the ledger UTxO than you free up with your transaction
This happens for all deposit schemes anyways.

**Comment by polinavino** [comment]
Similar to Shelley, all UTxOs must contain a minimum amount of ada, with the minimum amount for that UTxO depending on its size.
