### ISSUE TITLE
Native currency (Ada) values for CurrencyID and Token for multicurrency 

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1102]
What should these be?
I have started using `ScriptHash crypto` for the types of both of these, does this make sense?
If so, what script should be hashed for either?

**Comment by michaelpj** [comment]
A couple of considerations from Slack:
- One possibility would be to pick something outside the range of the hash function, so there's absolutely no way we could forge Ada via the multicurrency mechanism.
    - This should probably be the size of a normal hash, though.
    - A downside is that tools may try and be "helpful" and validate the field as a hash, potentially failing on an invalid hash.
- We could use the hash of an unspendable script, e.g. `error`.
    - I'm still a little bit scared that someone could get away with forging Ada if someone failed to run the script properly, or we have a bug in the evaluator.
- We could pick a random hash, and just rely on it never coming up.
    - This is probably totally safe, but makes me feel a little nervous. It'll be like people speculating about attacks on the special Ethereum address where destroyed currency goes...
    - Other hash collisions probably only let you forge ~1 transaction or so. But getting a hash collision for *this* hash would let you utterly break Cardano.

**Comment by michaelpj** [comment]
Oh, and to be clear: the token name can be literally anything. Why not `"Ada"`?

**Comment by polinavino** [comment]
I think a random hash is fine, and we could also add an extra explicit check in the rules to make sure there is no Ada forged just to be sure. 

`Ada` for Token sounds good i think

**Comment by michaelpj** [comment]
I think it's a little ugly to have an explicit rule against Ada being forged, it seems like we should be able to be cleverer than that, but I don't care massively.

**Comment by polinavino** [comment]
There is an explicit rule against forging ada, and a special case for ada in Value.
