### ISSUE TITLE
Implement MMM sum construction for KES

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#1117]
The current simple KES should be replaced with the iterative sum construction from the MMM paper to support the fixed number of iterations required (currently 128 = 2^7 iterations for the 90 days specified in the design doc for the operational keys)

**Comment by mgudemann** [comment]
This will be replaced with the real KES implementation which will provide an API callable from Haskell.

**Comment by JaredCorduan** [comment]
I'm going to close this since we will probably be wrapping a c library instead.
