### ISSUE TITLE
Error mnemonic of track of the snapshots!

### ISSUE THREAD

**Issue by Yang123321** [input-output-hk/cardano-ledger-specs#1200]
![IMG_20200210_142909](https://user-images.githubusercontent.com/20609008/74126397-c6ffda00-4c12-11ea-900c-07757aee0b40.jpg)

**Comment by JaredCorduan** [comment]
Why do you think that it is not correct?

**Comment by Yang123321** [comment]
![IMG_20200211_102152](https://user-images.githubusercontent.com/20609008/74206966-89558c80-4cb8-11ea-9387-91419d9798a7.jpg)
![IMG_20200211_101937](https://user-images.githubusercontent.com/20609008/74206973-91153100-4cb8-11ea-8eba-aa23989d4688.jpg)

**Comment by Yang123321** [comment]
![IMG_20200211_102934](https://user-images.githubusercontent.com/20609008/74207214-98890a00-4cb9-11ea-9cf4-7aadd7bf381d.jpg)

**Comment by JaredCorduan** [comment]
Apologies if i am misunderstanding, but I still do not see a problem. If you look at the examples, you can see the snapshot `snapEx2C` ([here]()https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/test/Examples.hs#L708) be set to mark it block [three](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/test/Examples.hs#L783), set in block [five](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/test/Examples.hs#L883), and go in block [seven](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/test/Examples.hs#L1012).

**Comment by Yang123321** [comment]
YES.you Are correct!
The snapshot take at (A) is different label at different epoch.
epoch (i-1) ...... "mark"
epoch (i) ...... "set"
epoch (i+1) ...... "go"

**Comment by JaredCorduan** [comment]
> YES.you Are correct!
:relieved: 

> The snapshot take at (A) is different label at different epoch.
exactly!

Thank you for taking such a close look at this!
