### ISSUE TITLE
Processing Shelley-era transactions, UTxO entries, and blocks 

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1205]
There will come a time when mempools might have both Shelley and Goguen type transactions. This would mean possibly accommodating Shelley-type transactions in Goguen blocks. 

We might also need to process Shelley blocks during Goguen times. Like, for example, even just replaying them to get the current ledger state.

What is the best way to handle this?

How do we handle the fact that the UTxO will now have a different type of outputs?
I.e. they will have a creation slot number, and they may have a data value hash. 
Would it make sense to have new constructors of `TxOut`, such as 
`TxOutG Address Value SlotNo | TxOutPlc Address Value HashData SlotNo | TxOut Addr Value`

Also, to accommodate existing UTxO entries full of `Coin`, the type `Value` has to have `Coin` as one of its constructors too
`data Value = (proper multicurrency Value constructor) | Coin Integer`  

How does the set of protocol parameters get updated?

**Comment by mchakravarty** [comment]
To be honest, I don’t think it is a good idea to try to support nodes that can handle two types of transactions. I think, it adds a lot of complexity. I understand that switching over from Shelley to Goguen is also painful, but at least it is a one-time pain point.

**Comment by michaelpj** [comment]
Surely this is a very similar question to "how do we get from Byron to Shelley"? I assume Duncan has thought about this already.

Also, I think Goguen only really adds stuff, so presumably we can write a `ShelleyTx -> GoguenTx` function that preserves validity. Then a Goguen node can just run that on any Shelley transaction it sees and just carry on.

**Comment by polinavino** [comment]
I hear there is a special "Shelley" or "Byron" tag depending on the era of the transaction. Where does this tag go? Who applies it? Does that mean it wont be possible to process Shelley transactions during Goguen? Do we still want to do this (i see above that Manuel is against the idea)? And if it is possible/desirable to do, what components need changing - is there anything but the ledger?

**Comment by polinavino** [comment]
UTxO is translated to next-era UTxO
Shelley blocks are not acceptable after Shelley
Shelley-era transactions need to keep their era tag for deserialization during Goguen
