### ISSUE TITLE
Adding the first slot of the Goguen era as the creation slot in UTxOs

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1232]
The Goguen UTxO entries will include the slot number in which the entry was created.

In the transition from Shelley to Goguen, is there any problem with putting the creation Slot of all the existing entries as the first slot of Goguen??

**Comment by michaelpj** [comment]
We noted that this is technically incorrect information, as the real creation date will have been earlier than that. However, I can't think of any reason this would make things go wrong.

**Comment by nau** [comment]
Why not just assign correct creation slots for all UTxO entries?
AFAIK all nodes implementations keep a whole blockchain, so it should be relatively easy to calculate correct values.

**Comment by polinavino** [comment]
This data definitely exists, and this should be possible. I think we concluded that this needs more discussion about whether it is too inconvenient to add the right slots to justify not doing that (or whether adding the first Goguen slot will cause too many problems)

**Comment by polinavino** [comment]
The other option is making the UTxO have outputs have type 
`ShelleyUTxOOutputs U GoguenUTxOOutputs`

**Comment by polinavino** [comment]
The slot creation feature is not needed
