### ISSUE TITLE
Non Integral calculations in Plutus

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1247]
In the Shelley ledger update rules, there are non-integral calculations performed (calculations of deposit decay for e.g.), the precision of these kinds of calculations must be consistent. For how this is done, see 
https://hydra.iohk.io/build/779843/download/1/non-integer-calculations.pdf

https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/dependencies/non-integer/src/NonIntegral.hs

If there are any such calculations in Plutus possible (e.g. a lot of the Actus contracts would have exponentiation to non-integer powers), they should 
be done the same way they are done in the Shelley ledger. This is a matter of 
deterministic script validation outcomes. Inconsistent rounding could 
result in different validation outcomes running the same script on the same 
arguments.

**Comment by michaelpj** [comment]
We don't have non integral built-in types in Plutus. Users can define their own (e.g. a rational type) but then it's up to them to get it right.

If we provided such a type in a library or added it as a built-in then we'd need to care about this, but I don't think there's anything to do at the moment.

**Comment by polinavino** [comment]
Nothing to worry about for ledger
