### ISSUE TITLE
IsValidating tag to be applied by block creators

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1248]
The `IsValidating` tag is part of each transaction, but it is added to the transaction by the creator of the block which contains this transaction.

This tag signifies whether all Plutus scripts in the transaction validate (note that when not all scripts validate but the transaction is otherwise valid, the transaction can still be processed to only pay the script-running fees). 

Whatever the tag says, it is always checked when processing each transaction: all scripts are run, and if they all validate, the tag must be `Yes`. If there is a script that doesnt validate, the tag must be `Nope`. If this tag is applied incorrectly, the whole transaction is invalid and the block is thrown away. 

There needs to be a mechanism by which the creator of the block applies this tag when making a block (after running the scripts to figure out what the correct tag is)

**Comment by JaredCorduan** [comment]
closed by #2264
