### ISSUE TITLE
Properties for the Goguen ledger

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#1284]
- No Ada is forged/unforged

- When a Tx is processed as "paying script fees only", no changes to the ChainState are made except the UTxO and fee pot (for-fees outputs moved to fee pot)

- The general accounting property still holds when a transaction only pays fees

- Shelley era transactions are always processed fully if they are processed at all

**Comment by WhatisRT** [comment]
- If a transaction adds outputs to the UTxO, all its Plutus scripts validate
- If a Plutus script does not validate, the transaction cannot add outputs
- If a transaction does not forge tokens, the Shelly accounting property holds, with Coin replaced by Value

**Comment by polinavino** [comment]
all ada should be fungible with other ada

**Comment by WhatisRT** [comment]
That depends a bit on the definition of Ada though. If Ada is any token with the PolicyID of Ada, that's only true if there is only one AssetID that's 'populated'. Ada could also mean a specific PolicyID and AssetID, in which case that's not a very strong property.

**Comment by polinavino** [comment]
More :
Tx has a (unique?) redeemer for everything that needs a redeemer
Epoch boundary should not affect MAs

**Comment by JaredCorduan** [comment]
* if a transaction is valid, it will remain valid if you increase the execution units
* if a transaction contains at least one valid script, it must have at least one execution unit
* `txvaltag tx` is true IFF all the scripts inside it validate within the given execution units
* if `txvaltag tx` is false, then the delegation state and the update state are unchanged
* if `tx` is a "shelley in goguen" transaction, the only difference between processing `tx` and processing `toGoguenTx tx` (ie converting it out of band) is that the transaction id on the created outputs is different.

**Comment by WhatisRT** [comment]
Hashes of all data passed to scripts are included either in the UTxO or in the transaction. We say this in the spec, but it's not super obvious that this is actually true.

**Comment by JaredCorduan** [comment]
I'm going to close this now since we have the list of properties in the spec.
