### ISSUE TITLE
Performance of new pools/pools with no stake

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-ledger-specs#1295]
We need to get a definitive decision on how to initialise the apparent performance for new pools, and how to handle pools with zero stake (or so little stake that they are expected to produce less than one block).

The design document proposes to initialise the apparent performance with the median of the apparent performance of the top `k` pools. This has the downside that half of those top `k` pools could improve their apparent performance by re-registering their pool (which of course does have its own downsides, losing delegates and reputation).

I just had a call with @JaredCorduan, who is currently implementing the apparent performance calculation, and needs a decision on this.

What I would propose is to go ahead and do use the median of the competitive pools apparent performance, but highlight the pools in the wallet listing, to make it clear to the users that this pool _looks_ to be attractive, but we do not yet know about its performance.

**Comment by JaredCorduan** [comment]
we have solved this with the hit-rate estimation
