### ISSUE TITLE
Stake Pool Relays

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#1368]
The stake pool relays (in the pool registration cert) should not be a list of urls. We need to decide what exactly we want and implement it.

In CDDL, we probably want something more like a list of:
```
relay = [ port: uint / null
        , dnsname: tstr .size (0..64)
        / ipv4: bytes .size 4
        / ipv6: bytes .size 16
        ]
```

**Comment by dcoutts** [comment]
So we've concluded we want something corresponding to this Haskell type
```
type StakePoolRelays = [StakePoolRelay]
data StakePoolRelay =
     SingleHostAddr (Maybe IPv4) (Maybe IPv6)  -- ^ One or both of IPv4 & IPv6
   | SingleHostName DnsName                    -- ^ An @A@ or @AAAA@ DNS record
   | MultiHostName  DnsName                    -- ^ A @SRV@ DNS record
```

**Comment by dcoutts** [comment]
Oh I forgot to include the optional port number. Each of the three forms of the `StakePoolRelay` can have an optional port number.

And as above, IPv4 can be a 4 byte bytesting IPv6 size 16, and the dnsname is up to 64 byte text.
