### ISSUE TITLE
Move genesis delegation adoption to TICK rule

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#1390]
New genesis key delegations are currently adopted in the `LEDGERS` transition, in the base case. This is unfortunate for the consensus integration, and would cause the header validation properties to fail. We should move this to the `TICK` transition.

**Comment by tatyanavych** [comment]
PR https://github.com/input-output-hk/cardano-ledger-specs/pull/1395
