### ISSUE TITLE
Fix occasional Heap Exhaustion in Tests

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#1392]
If a property fails and a counterexample (of a Trace) is too large to display, then we get a Heap Exhaust error.

This sometimes happens even for traces with no signals, but "large" initial state.

A few things to do about this:

* to the extent possible, further limit size of generated initial state for LEDGER and CHAIN traces
* Implement custom Show instances for CHAIN/LEDGER Traces that are more compact and limited in max size

**Comment by JaredCorduan** [comment]
I had to increase the heap size again to get #1405 through. This was a pretty small PR, and I can guess why it would increase things. It changes the `txsize` function to use serialization, so the lazy bytestrings that are used for the annotated decoders are being realized now.
