### ISSUE TITLE
Serialize reward accounts as addresses

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#1434]
Currently reward accounts are serialized exactly as the underlying stake credential. We want to be able to serialize them as addresses.

In the 8-bit header, the 4-bit network ID will be exactly as the other addresses, but we will use two of the future format address `1001 - 1111` to indicate the single key and script staking credentials. The remainder of the address is just the credential hash.

**Comment by nc6** [comment]
Is this resolved by #1491?

**Comment by JaredCorduan** [comment]
> Is this resolved by #1491?

yes, thanks!
