### ISSUE TITLE
Include missing witnesses with MissingVKeyWitnessesUTXOW error

### ISSUE THREAD

**Issue by intricate** [input-output-hk/cardano-ledger-specs#1456]
Might it be worthwhile to include the missing witnesses as part of the `MissingVKeyWitnessesUTXOW` error?

From the node's point-of-view, seeing an error like `ApplyTxError [LedgerFailure (UtxowFailure MissingVKeyWitnessesUTXOW)]` after submitting a transaction with many inputs, certificates, etc. might not be as helpful as it could be.

Thoughts?

cc @dcoutts @erikd

**Comment by erikd** [comment]
I agree, The error messages should at least specify how many witnesses were expected and how many were missing.
