### ISSUE TITLE
Analyse the effect on the moving average on the preservation of the total reward amount 

### ISSUE THREAD

**Issue by jcmincke** [input-output-hk/cardano-ledger-specs#207]
**Source : Ledger specs, v 1.0 , Fig 31**

The delegation paper guarantees that the sum of all max pool reward is always < R.

However, in poolRew function, we have : *pool reward = avg ^ gamma . mapPoolReward*.

So we have to make sure that  *avg ^ gamma < 1*. 

It seems reasonable to suppose that the value of *avg* will be around 1 (on average) but it can be > 1. 
And then, *avg ^ gamma  > 1*.

**Comment by dnadales** [comment]
@kantp @JaredCorduan is this something we still have to check?

**Comment by kantp** [comment]
No, this is fine, since the moving average will not have an effect on the actual reward payouts, only on the ranking of the pools. If the moving average were used in the payout calculation, we would have a problem here (which is the reason we are not using it for the payout calculation).
