### ISSUE TITLE
Integrate executable ledger spec into consensus layer

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-specs#241]
(This is a migration of https://github.com/input-output-hk/cardano-chain/issues/240 to this repository.)

This covers the first integration point between the consensus layer and the ledger layer.

The consensus layer expects a function which takes a block and an existing chain and attempts to produce a new chain. We should be able to instantiate this with the executable chain spec. It may currently require us to ignore some parts of chain validation which are not implemented (e.g. updates) and we may need to implement a few more things on the chain level (e.g. epoch transitions).

**Comment by dnadales** [comment]
@mdimjasevic does this belong to `ledger_impl_validate_api`:

![image](https://user-images.githubusercontent.com/175315/54025377-a1fd1e80-419a-11e9-9d6d-b073c91a4330.png)


If so we might want to add an epic for it, and put this issue inside it.

**Comment by dnadales** [comment]
As far as I understand we're not doing this anymore, so I took the liberty of closing this one.

@mdimjasevic , @ruhatch or @nc6 : if we still need this please re-open.
