### ISSUE TITLE
Specs are everywhere

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#251]
... could be the title of a book written by our team, but in this case this issue refers to the fact that we have:

- Formal specs in the `latex` and `specs` directories.
- Executable specs in the `hs` and `specs` directories.
- Design documents and other stuff in the `docs` directory.

We should:

- [ ] Define one place where formal specs should be and move everything there.
- [ ] Define one place where executable specs should  be and move everything there.
- [ ] Determine whether `docs` is the right directory for the design document.
- [ ] Consider renaming `delegation_design_spec` to `delegation-design-spec` for the sake of consistency with other directories in our repo.
- [ ] Consider moving `accounting` somewhere else.

:ant: :heart: :running_man:

**Comment by mgudemann** [comment]
@dnadales isn't this resolved for at least a large part of it?

**Comment by dnadales** [comment]
Indeed! Thanks @mgudemann for checking this.

Closed by #368
