### ISSUE TITLE
Define the minimum amount of environment needed for the update interface rules

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#285]
Currently there is a common environment for all the update interface rules. This leads to a situation in which users of these rules have to pass unnecessary information around. So it seems better to have different environment types for the different update rules. Another advantage of this seems to be that we're more specific about which information each rule is using, which means readers of the rules don't have to keep unnecessary information in their heads.

**Comment by mdimjasevic** [comment]
What are environment rules?

**Comment by dnadales** [comment]
> What are environment rules?

Possibly a brain fart.

I corrected the description.

**Comment by mdimjasevic** [comment]
Would this entail updating the STS framework?

**Comment by dnadales** [comment]
I don't think so. This concerns the update interface rules only.
