### ISSUE TITLE
ledger_spec_old

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#288]
Define `LaTeX` and executable specifications of the blockchain and ledger layer for the (simplified) rules for the existing chain.

**Comment by mdimjasevic** [comment]
@dnadales, can you please elaborate what is this issue about?

**Comment by dnadales** [comment]
It is the same epic we had in `cardano-chain`, which was moved here. This corresponds to one of the nodes in Duncan's diagram.

**Comment by mdimjasevic** [comment]
Ok, someone knows what is this about.

**Comment by dnadales** [comment]
> Ok, someone knows what is this about.

Weren't you there when we were defining the epics? A couple of moths ago? Together with Ben? We use epics to group together issues. In this particular case this epic groups all the issues required to:

> Define LaTeX and executable specifications of the blockchain and ledger layer for the (simplified) rules for the existing chain.

**Comment by dnadales** [comment]
Closing this Epic as it doesn't seem to be relevant anymore.
