### ISSUE TITLE
Operational key/certificate lifetime

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/cardano-ledger-specs#290]
Hello! This part in the delegation design spec about operational key lifetime is a bit confusing:

https://github.com/input-output-hk/fm-ledger-rules/blob/409e46a4ede339975bd5d64dc5498e93bd62a3ce/docs/delegation_design_spec/delegation_design_spec.tex#L1226-L1233

![image](https://user-images.githubusercontent.com/5585355/53880908-4bb99f80-4023-11e9-8683-7eebb6f6946f.png)

It states that operational **key** lifetime is 128 days, but operational key **certificate** lifetime is 90 days. Does this mean that when a pool operator creates a key an a certificate that delegates to this key - after 90 days the certificate will expire, but key will still be operational for 38 more days, so they **can** (not should) sign a new certificate that delegates to the same hot key, but then in 38 more days the key will stop working, even tho the certificate will still be **as if** valid by its lifetime?

What is the reason for having these lifetimes offset like this? And why there's a reason to have separate certificate lifetime, if key expiration would ensure certificate has to be replaced too?

Thank you!

@kantp

**Comment by dnadales** [comment]
@kantp was this addressed already?

**Comment by JaredCorduan** [comment]
The 90 days was a business decision. the 128 was just the lowest power of two that worked. :)
