### ISSUE TITLE
likely incorrect term in recently updated section about staking pool metadata servers

### ISSUE THREAD

**Issue by rooooooooob** [input-output-hk/cardano-ledger-specs#294]
Why would we be looking up by the private key? Is this a mistake? I assume it was meant to be vks or hash(vks) or something other than the plain private staking key.

https://github.com/input-output-hk/fm-ledger-rules/blob/026956319dae1af26bd58d6abdff05a80f11ddf6/docs/delegation_design_spec/delegation_design_spec.tex#L2286

https://github.com/input-output-hk/fm-ledger-rules/blob/026956319dae1af26bd58d6abdff05a80f11ddf6/docs/delegation_design_spec/delegation_design_spec.tex#L2318

**Comment by JaredCorduan** [comment]
The first item above was fixed by https://github.com/input-output-hk/cardano-ledger-specs/commit/e061e1dec65c51ee7a2a415f3d4aba53fb3c50a5
