### ISSUE TITLE
Federate protocol parameters in the ledger spec

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#344]
Currently the set of required protocol parameters for the ledger spec is defined in the "Update" section. In the chain spec I have introduced "federated" protocol parameters which are defined alongside the relevant system, along with the type of the value.

This issue would cover:
- Introducing the (slight abuse of) notation used to define these.
- Moving the ledger spec parameters to the relevant places.

**Comment by dnadales** [comment]
@nc6 I'm not sure what is intended here. [Right now](https://github.com/input-output-hk/cardano-ledger-specs/commit/5e197bdaeecc6494abedb09c12b771e502de68d8) I added a protocol parameters section to the chain spec, but I'm thinking we could put this section in the ledger spec, and refer to it from the former. Would that make sense?

**Comment by nc6** [comment]
https://github.com/input-output-hk/cardano-ledger-specs/commit/5e197bdaeecc6494abedb09c12b771e502de68d8 seems to go in exactly the opposite direction to what was intended in this issue :-(

**Comment by dnadales** [comment]
We can still revert it back. But I want to make sure I understand what you want :) 

My rationale for having all the parameters defined in a single place is to be consistent with the way we define things in the Shelley spec, where all the related definitions (e.g. addresses are put in a single place). I'm fine with both approaches as long as we are consistent.

If we scatter the protocol parameters across sections, would this be what you had in mind:

- A section describing protocol parameters (or we can just refer to the Byron ledger spec)
- When we use a protocol parameter we define it as belonging to `Ppm` and given their type, as I did here (but in this case `maxBlockSize` and `maxHeaderSize` would appear in the sections where they're used):

![image](https://user-images.githubusercontent.com/175315/56728122-63272600-6752-11e9-998c-a772daabf30f.png)

**Comment by dnadales** [comment]
After a long slack discussion it seems we settled on using a compact and consolidated definition of protocol parameters. @nc6 is [this](https://github.com/input-output-hk/cardano-ledger-specs/pull/425/commits/9d8acf64594802d0c19822709ea3c33a96a48e05) enough to close this?
