### ISSUE TITLE
Give the repository a better structure

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#347]
Byron specifications are located in `specs`, whereas Shelley specifications are located in the `latex` and `hs` top level directories. This is confusing and people not familiar with the repository structure will certainly struggle to find where things are.

## Proposed solution

We could set up the following directory hierarchy:

- `byron`: Byron formal and executable specifications
  - `ledger`:
    - `formal-spec`: previously-called `latex`
    - `executable-spec`: previously called `hs`
  - `chain`
    - `formal-spec`
    - `executable-spec`
- `shelley`:
  - `design-spec`: previously called `delegation_design_spec`
  - `ledger`:
    - `formal-spec`: previously called `latex`
    - `executable-spec`: previously called `hs`
    - `dependencies`
  - `chain`: for future work on the chain spec

## Next Actions

- [x] Adapt the repository according to the proposed solution
- [x] Update the README by better explaining what this repo contains, and  where everything is.
- [x] Remove `lhs` directory if not needed (CC: @JaredCorduan )

**Comment by dnadales** [comment]
CC: @kantp @JaredCorduan @mgudemann @nc6

**Comment by kantp** [comment]
Thanks, @dnadales, I think the structure you propose makes sense.

**Comment by JaredCorduan** [comment]
Are we sure we want to keep the `Byron` and `Shelley` distinction forever? Or do we still wish to merge them at some point?

As for the `lhs` directory, I'm confused how it made its way to master, I thought it was in a branch.  Yes, it should be removed, along with `latex/lhs2tex/`

**Comment by dnadales** [comment]
> Are we sure we want to keep the Byron and Shelley distinction forever? Or do we still wish to merge them at some point?

I think this is a crucial question for this issue!

It depends on the goal for these specifications. I think they will likely be read by developers implementing them (although we had some questions from Ruslan and others I think). If this is the case then anyone wanting to implement the cardano ledger will have to implement both specs, so maybe we can keep the two specs separate.

Any thoughts on this? We should also ask @dcoutts on slack, since github mentions to him go to `/dev/null` :)

**Comment by dcoutts** [comment]
In the long run we want the combined Byron+Shelly spec that covers the validity of the chain from genesis, though the Byron rules, and across a hard fork into the Shelley rules.
