### ISSUE TITLE
Review Formal Spec of the Cardano Ledger

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#365]

**Comment by uroboros** [comment]
Review the spec for:

- typos / basic line-editing
- inconsistencies that might have crept in
- concepts mentioned before being introduced
- areas that might need more explanation (or references to other IOHK specs)

**Comment by mdimjasevic** [comment]
Is this still permissive BFT-specific, as the issue title suggests?

**Comment by mdimjasevic** [comment]
I'll leave some comments here, because they do pertain to permissive BFT.

In the chain specification (available in the `specs/chain/latex` directory of this repository), the `PParams` name is used, but never defined nor referenced as defined in another document. It looks like the name is defined in the specification available in `specs/ledger/latex`.

**Comment by mdimjasevic** [comment]
The `DIState` name is also not defined in `specs/chain/latex` nor referenced.

**Comment by mdimjasevic** [comment]
The `SIGCNT` STS as defined in Figure 10 in `specs/chain/latex` looks wrong to me. The `filter` function as used there is never defined, but if `filter p xs` is assumed to be returning only elements of `xs` that satisfy the predicate `p`, then `| filter (=vk_g) sgs' |` will count blocks signed that are outside the moving window of size `k`. The state `sgs'` just keeps on getting bigger and bigger, keeping track of absolutely all blocks instead of only the last `k` blocks. In an earlier version of the spec I addressed this issue by keeping track of genesis signers in a queue, but someone removed the queue without checking if that breaks the logic of the rule.

**Comment by uroboros** [comment]
> Is this still permissive BFT-specific, as the issue title suggests?

just fixed the title, thanks

**Comment by mdimjasevic** [comment]
In section 5.2 of the Specification of the Blockchain Layer (Byron era), point 6 says: "Finally, we verify and update the signature count rules." Instead, it should say something like: "Finally, we verify and update the state according to the signature count rules."

**Comment by mdimjasevic** [comment]
`bhissuer` should be renamed to `bhIssuer`.

**Comment by mdimjasevic** [comment]
In Figure 12 of the Specification of the Blockchain Layer (Byron era), the `PBFTEnv` type's `ds` should be of type `Map VKeyGenesis VKey` instead of `DIState` (that is, its LaTeX equivalent).

**Comment by mdimjasevic** [comment]
In Figure 6 of the Byron chain specification, the type of the environment for the `EPOCH` STS should be a map from `VKeyG` to `VKey`, and not from `VKeyG` to `VKey`.

**Comment by mdimjasevic** [comment]
In Figure 17 of the Byron chain specification, the environment passed to the `EPOCH` STS is `pps us`, which I suppose is of type `PParams`. However, the type of the environment for the `EPOCH` STS as defined in Figure 6 is of type `Map VKey VKeyG`, which is obviously (quite) different. Hence, there's a mismatch that needs to be addressed.

**Comment by mdimjasevic** [comment]
In Figure 23 of the Byron chain specification, the environment passed to the `PBFT` STS contains `ds` for the second component, which is of type `DIState`, while `PBFT` at this place expects a term of type `Map VKeyGenesis VKey`. Probably this should be `_dIStateDelegationMap ds` instead.

**Comment by mdimjasevic** [comment]
In Figure 23 of the Byron chain specification, the signal sent to the `PBFT` STS is `bh`, which is undefined. It should be `bHead b` instead.

**Comment by mdimjasevic** [comment]
The `UPIState` type is out of sync: the Haskell counterpart has an `Epoch` element in it, while the LaTeX counterpart does not.

**Comment by mdimjasevic** [comment]
The `UPIEC` STS in the Ledger spec for the Byron-Shelley era has no signal in its LaTeX counterpart. Therefore, in Haskell it should be the unit type/value.

**Comment by dnadales** [comment]
Maybe we should make separate issues, one for each spec, and add checklists so that we can keep track of what was already addressed. Does that make sense?

**Comment by dnadales** [comment]
@mdimjasevic I think your comments regarding the specs are now addressed. I marked them with :rocket:. :rocket: is the new :heavy_check_mark: :)

**Comment by mdimjasevic** [comment]
The `UPIEC` STS in the Ledger spec for the Byron-Shelley era has no signal in its LaTeX counterpart. Therefore, in Haskell it should be the unit type/value.

**Comment by mdimjasevic** [comment]
> @mdimjasevic I think your comments regarding the specs are now addressed. I marked them with rocket. rocket is the new heavy_check_mark :)

Great, thanks for this! Where do I see the rockets?

**Comment by dnadales** [comment]
> Great, thanks for this! Where do I see the rockets?

In the sky :P 

![image](https://user-images.githubusercontent.com/175315/56721433-299bee00-6745-11e9-95f4-e4e065900420.png)

**Comment by mdimjasevic** [comment]
In the Byron-Shelley era chain specification in "Figure 18: Block body processing types and functions", the definition of the `bEndorsment` function should be `bEndorsment b = (bProtVer b, (bhIssuer . bHead) b)` instead of `bEndorsment b = (bProtVer b, bhissuer b)`.

**Comment by mdimjasevic** [comment]
In the Byron-Shelley era chain specification in "Figure 2: Update interface processing types and functions", the type of `BUPISig` is not in line with the type of the `endorsment` function used in the `BBODY` STS. They're isomorphic, but not equivalent. I suggest changing `BUPISig`'s type to `(Maybe UProp, [Vote], (ProtVer, VKey))` (the last component of the tuple is `(VKey, ProtVer)` at the moment).

**Comment by mdimjasevic** [comment]
The `PVBUMP` STS in the ledger spec of the Byron-Shelley era does not have its type listed explicitly, which makes it harder to read the spec.
