### ISSUE TITLE
Does giving full rewards, regardless of `d` value, create an incentive for stake pool operators to miss slots?

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-specs#367]
https://github.com/input-output-hk/cardano-ledger-specs/blob/a4d67fb46f8ceafd9c17c3eb012677ffac4a721d/docs/delegation_design_spec/delegation_design_spec.tex#L1625-L1630

https://github.com/input-output-hk/cardano-ledger-specs/blob/a4d67fb46f8ceafd9c17c3eb012677ffac4a721d/docs/delegation_design_spec/delegation_design_spec.tex#L1649-L1662

From these above quotes, it seems to me that "rational and disloyal" stake pool operator (or set of operators) might intentionally miss slots in order to keep `d` from decreasing. This would allow them to do less work, while receiving the same rewards payout.

The counterargument I expect to this is that since we are Proof of Stake, the marginal cost of mining more blocks is very low, so the economic motivation is pretty small.

Still, I wanted to bring this up because I'm curious if it's been thought of.

**Comment by JaredCorduan** [comment]
@kantp can correct me if I am wrong.  Pools will still be penalized for under-performing, it's just that their rewards are relative to the "decentralized stake". In the example at the end of section 4.9.2, it talks about a pool with 1% stake with d=0.9 needing to produce 21.6 blocks.  If this pool only produced 10 blocks when d=0.9, it would be penalized as normal (section 6.5.1). The point of the comment is just that producing 22 blocks (when d=0.9) is easier than producing 216 blocks (when d=0), thought the rewards are the same.

**Comment by JaredCorduan** [comment]
But perhaps you are saying this: for some pool with some distribution, it's _better_ for them to miss some amount of blocks, which they are penalized for, in order to keep `d` from decreasing and thus keep this not-yet-decentralized boost to their relative stake.  In which case, yes, I think your counterargument is correct, namely that at the time that we are decentralizing there is very little cost to mining these blocks.

**Comment by mhuesch** [comment]
> @kantp can correct me if I am wrong. Pools will still be penalized for under-performing, it's just that their rewards are relative to the "decentralized stake". In the example at the end of section 4.9.2, it talks about a pool with 1% stake with d=0.9 needing to produce 21.6 blocks. If this pool only produced 10 blocks when d=0.9, it would be penalized as normal (section 6.5.1). The point of the comment is just that producing 22 blocks (when d=0.9) is easier than producing 216 blocks (when d=0), thought the rewards are the same.

Ah, I misunderstood how penalties will be enforced as normal. So that clears up my question, in addition to the counterargument about low marginal cost on mining blocks. There could possibly be a pool & distribution for which it's rational to miss slots, but it doesn't seem like much of a concern.

Thanks!
