### ISSUE TITLE
Decision: exclude pool that don't honour their pledge from protocol?

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-ledger-specs#385]
In the current design, a pool where the owners have pledged stake to increase their rewards will be excluded from the protocol if the owners fail to delegate that much stake.

We could also consider just stripping the pool of its rewards. We would then rely on pool members to re-delegate for the Sybil protection.

**Comment by vantuz-subhuman** [comment]
I am no expert on these questions, but it sounds weird to a common person, like making Sybil protection itself more "human dependant" than "mechanical".

**Comment by kantp** [comment]
We discussed this during the delegation session at the company meeting. We agreed that excluding pools that do not meet their pledge from the protocol (until they possibly meet their pledge in a future epoch), as written in the current spec, is indeed the correct thing to do.

In addition, the delegation centre should suppress the listing of pools that currently do not meet their pledge, unless the user specifically asks for them to be included in the listing.
