### ISSUE TITLE
Decision: How exactly should we handle cold wallet staking keys

### ISSUE THREAD

**Issue by kantp** [input-output-hk/cardano-ledger-specs#387]
We'll need a UI feature for giving the staking key of a cold wallet to a user, so that they can post certificates for it from another wallet.

We should check with the researchers that this does not create any security issues.

**Comment by vantuz-subhuman** [comment]
I had a question just about that recently, good chance to ask it 😁The question was - how should use pay fees to post staking certificates, if payment key from the wallet is offline. So the idea is that a staking key from wallet A (cold) might be "imported" into client program with restored wallet B (hot), right? So user will be posting certificates for A and pay from B?

**Comment by kantp** [comment]
Indeed, that's the plan for cold wallets and delegation. This issue is here to remind us that we have to talk to the UI team, to figure out the best solution for the users.

**Comment by kantp** [comment]
I talked to Darko at the company meeting, he tells me that the Daedalus team is already planning for a more general mechanism to share staking keys between different wallets, so that users can handle delegation for multiple wallets more easily. This is just a special case.
