### ISSUE TITLE
Shelley-Byron protocol parameters

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#393]
Protocol parameters are defined a bit differently in Byron than in Shelly. In Shelley they are defined like the other ledger state is defined, but in Byron the protocol parameters are a key-value map. We should be consistent between the two specs, especially since we are going to be using/referencing the `BUPI` transition is Shelley as in #390 

Additionally, we should make sure that common parameters are named the same thing, such as `maxBlockSize` and `maxHeaderSize` from the Byron chain spec, etc.

The parameter that will perhaps be the trickiest to handle is `k` (or the related `slotsPerEpoch`). This is handled differently in the two specs.

**Comment by dnadales** [comment]
I made some [preliminary notes](https://drive.google.com/file/d/1JwRgDXAEekpPL1bCanMJqEWcM2dP_ioF/view?usp=sharing) on what we could change to make the two specs match. It doesn't look that hard.

One of the main questions I have is whether we want to make the number of slots per-epoch variable in Shelley, in which case we'd need to keep track of the history of all the epoch lengths.
