### ISSUE TITLE
Small changes to Byron blockchain spec from implementing CHAIN

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-specs#409]
### `EPOCH`
- `e_c` is unused in the state and should be moved to environment

### `BHEAD`
- `elens` unused (I think this has been discussed elsewhere)

### `BBODY`
- `verify` used, but the proofs are hashes, rather than signatures
- `UTXOW` takes a single transaction - need a sequencing rule for transactions
- `pps` in environment unused, but taken from `us` instead

**Comment by dnadales** [comment]
Thanks Ru!

**Comment by nc6** [comment]
In `EPOCH`, `e_c` is updated to `e_n` if there is an epoch change, hence being in the state...

**Comment by dnadales** [comment]
> In EPOCH, e_c is updated to e_n if there is an epoch change, hence being in the state...

But actually we don't need the updated value in the rule that uses it :)

**Comment by dnadales** [comment]
More information on:

> verify used, but the proofs are hashes, rather than signatures

In Rule:

![image](https://user-images.githubusercontent.com/175315/56678595-632c1500-66c3-11e9-87e5-3c46462dcd23.png)

We should:

- change:
  - `bhUtxoSig` to `bhUtxoProof bh \in Hash`
  - `bhDlgSig` to `bhDlgProof bh \in Hash`
  - `bhUpdSig` to `bhUpdProof bh \in Hash`
- do a Hash comparison:
  - `hash bUtxo == bhUtxoProof bh`
  - etc


￼

**Comment by mdimjasevic** [comment]
I've been working on implementing the spec (including this rule) in Haskell based on the current version. Can you notify me when you create a PR so I'm aware of it?

**Comment by dnadales** [comment]
> I've been working on implementing the spec (including this rule) in Haskell based on the current version. Can you notify me when you create a PR so I'm aware of it?

Sure. You'll be among the reviewers.
