### ISSUE TITLE
upAdptThd and t are the same so only one should be used

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-specs#465]
In the specifications for the Byron-Shelley era, both `upAdptThd` and `t` are used to refer to the same thing. Update the specifications such that only one of them is used.

**Comment by dnadales** [comment]
Can you post a screenshot of which rules you're referring to? Then we can quickly spot the places where these discrepancies occur and fix them fast.

**Comment by mdimjasevic** [comment]
The specifications have to be thoroughly scanned in their entirety to make sure these changes are consistent across the whole specifications as their usage is not in one place only.

**Comment by dnadales** [comment]
This rule needs to be corrected, `q` is not used anywhere:

![image](https://user-images.githubusercontent.com/175315/58184057-abcdf280-7cb0-11e9-9542-cbbbc162d7c5.png)

`t` should be in the environment

![image](https://user-images.githubusercontent.com/175315/58184165-e33c9f00-7cb0-11e9-88c9-d16431f286ee.png)

`t` should be a natural number

![image](https://user-images.githubusercontent.com/175315/58184213-f6e80580-7cb0-11e9-9ffb-667485e140a2.png)

**Comment by dnadales** [comment]
It seems we need to use `ngk` as we did in `UPIVOTE`:

![image](https://user-images.githubusercontent.com/175315/58184360-3e6e9180-7cb1-11e9-85e4-56df26fec418.png)
