### ISSUE TITLE
Remove the dms map from the EPOCH STS

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-specs#466]
In the Byron-Shelley era specifications, the `dms` map in the environment of the `EPOCH` STS is unused. Therefore, remove it.

**Comment by dnadales** [comment]
This doesn't concern the formal spec, does it? If so then we should remove the `formal-spec` label.

**Comment by mdimjasevic** [comment]
> This doesn't concern the formal spec, does it? If so then we should remove the `formal-spec` label.

I believe it does concern the formal specification, but feel free to check and act accordingly.

**Comment by dnadales** [comment]
> > This doesn't concern the formal spec, does it? If so then we should remove the `formal-spec` label.
> 
> I believe it does concern the formal specification, but feel free to check and act accordingly.

Well, you added the label, so that's why asked.

**Comment by mdimjasevic** [comment]
I added it because it affects the LaTeX specifications: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/chain/formal-spec/blockchain-spec.tex#L675

**Comment by dnadales** [comment]
Sorry I fail to see how does this change affects the specifications? Could you elaborate a bit?

**Comment by mdimjasevic** [comment]
Can you please take a look at the `EPOCH` STS and check where `dms` is used? That should answer your question.

**Comment by dnadales** [comment]
If you're saying

> I added it because it affects the LaTeX specifications: https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/chain/formal-spec/blockchain-spec.tex#L675

I'd expect that you have a justification for it, not that I should come up with one.

I need some help here as I'm trying to organize the issues, and labeling them correctly is important.

I'm removing the `formal-spec` label till it becomes clear if and how the spec is affected.
