### ISSUE TITLE
Formulate and implement properties for Byron-Shelley era spec STSes

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-specs#481]
The Byron-Shelley era specifications comprise state transition systems (STSes) that form a hierarchy as below. This milestone is for formulating and implementing properties for the STSes both in LaTeX and Haskell code. Due to dependencies as given by the hierarchy, the properties should be done in a bottom-up manner.

# CHAIN

### EPOCH

1.  UPIEC

    1.  PVBUMP

### BUPI

1.  UPIREG

    1.  UPREG
    
        1.  UPV
        
            1.  UPPVV
            
            2.  UPSVV

2.  UPIVOTES

    1.  UPIVOTE
    
        1.  UPVOTE
        
            1.  ADDVOTE

3.  UPIEND

    1.  UPEND
    
        1.  FADS

### DELEG

1.  SDELEGS

    1.  SDELEG

2.  ADELEGS

    1.  ADELEG

### UTXOWS

1.  UTXOW

    1.  UTXO

In Org-mode formatting the hierarchy would look like this:

```org
* CHAIN
** BHEAD
*** EPOCH
**** UPIEC
***** PVBUMP
** PBFT
*** SIGCNT
** BBODY
*** BUPI
**** UPIREG
***** UPREG
****** UPV
******* UPPVV
******* UPSVV
**** UPIVOTES
***** UPIVOTE
****** UPVOTE
******* ADDVOTE
**** UPIEND
***** UPEND
****** FADS
*** DELEG
**** SDELEGS
***** SDELEG
**** ADELEGS
***** ADELEG
*** UTXOWS
**** UTXOW
***** UTXO
```

**Comment by dnadales** [comment]
I will close this for now as we don't have the time nor the resources to go though this (in this way we can direct our focus better). We already checked the most important properties:

- No double spending
- The update mechanism allows to update software and protocol paramtetes
- Delegation allows to delegate
- No delegation certificate can be replayed.

I'd say, if we run into properties that we should test we could make separate issues for it.
