### ISSUE TITLE
Allow empty protocol update proposals in the Byron spec

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#492]
The actual Byron implementation allows for empty protocol update proposals, so the specs (formal and executable) should be adapted to reflect this.

**Comment by mdimjasevic** [comment]
@dnadales, isn't this already the case? Isn't Figure 4 of the chain specification it? Similarly, here it is in the executable counterpart: https://github.com/input-output-hk/cardano-ledger-specs/blob/682e23cd6fd28381f9a236c71b2dfe20f3bfbd90/byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Bupi.hs#L53

**Comment by dnadales** [comment]
No, this issue refers to updates in the protocol version without changing any protocol parameters. 

However after re-examining the rules, it seems that an empty update proposal, i.e. one where `upParams up = \emptyset` would pass the following validation rules:


![image](https://user-images.githubusercontent.com/175315/60955664-9749c600-a301-11e9-8b26-9c4c464ac653.png)

If that's correct we should close this issue.

**Comment by dnadales** [comment]
See comment above.
