### ISSUE TITLE
Change HashKey in KeyHash in all specs

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-specs#517]
We decided to rename HashKey to KeyHash across all of our specifications and the implementation. We should update:
- [ ] Byron formal spec
- [ ] Shelley formal spec
- [ ] Shelley executable spec

It appear that `HashKey` is not yet used in the Byron executable spec

**Comment by JaredCorduan** [comment]
when we make this change in the shelley ledger spec, we can also make sure we always use `KeyHash_pool` and `KeyHash_stake` instead of just `KeyHash`.

**Comment by JaredCorduan** [comment]
> when we make this change in the shelley ledger spec, we can also make sure we always use `KeyHash_pool` and `KeyHash_stake` instead of just `KeyHash`.

I made this a separate issue: #629
