### ISSUE TITLE
Fix HasTypeReps instances for Tx and TxWits

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#523]
Currently these are the definitions of `Tx` and `TxWit`:

```haskell
-- |A raw transaction
data Tx id = Tx { txid    :: id
                , inputs  :: [TxIn id]
                , outputs :: [TxOut]
                } deriving (Show, Ord)

instance HasTypeReps i => HasTypeReps (Tx i) where
  typeReps x@(Tx i' inputs outputs)
    = typeOf x <| typeOf i' <| typeOf inputs <| typeOf outputs <| empty

data TxWits id = TxWits
                { body      :: Tx id
                , witnesses :: [Wit id]
                } deriving (Show, Eq)

instance HasTypeReps i => HasTypeReps (TxWits i) where
  typeReps (TxWits b w) = typeOf b <| typeOf w <| empty

```

This is wrong since these instances are not counting the number of inputs, the number of outputs, and the number of witnesses.

As far as I can see, the default generic definitions would suffice, so we need to:

- [ ] Write unit tests for the expected `typeReps` of `Tx`s.
- [ ] Write unit tests for the expected `abstracSIze` of  `Tx`s.
- [ ] Optional: write property tests for the `typeReps` of `Tx`s.
- [ ] Optional: write property tests for the expected `abstracSIze` of  `Tx`s.
- [ ] Remove the custom implementation of the `HasTypeRep` `Tx` instance, and check that the tests pass.
- [ ] Write unit tests for the expected `typeReps` of `TxWits`s.
- [ ] Write unit tests for the expected `abstracSIze` of  `TxWits`s.
- [ ] Optional: write property tests for the `typeReps` of `TxWits`s.
- [ ] Optional: write property tests for the expected `abstracSIze` of  `TxWits`s.
- [ ] Remove the custom implementation of the `HasTypeRep` `TxWits` instance, and check that the tests pass.

**Comment by uroboros** [comment]
```
instance HasTypeReps i => HasTypeReps (TxWits i) where
  typeReps (TxWits b w) = typeOf b <| typeReps w
```

...would give a typeReps that includes the `[Wit]` types - currently `typeOf w` fixes on [Wit] and does not give a typeRep for each Wit in the list. 

Having said that, so would a generic instance.

**Comment by dnadales** [comment]
> Having said that, so would a generic instance.

Right. I'd prefer to use a generic instance whenever possible.

**Comment by uroboros** [comment]
For the `Hash` type, the newtype deriving used to derive the HasTypeReps instance does not give us what we need (for an explanation, see the comments about `Slot` in https://github.com/input-output-hk/cardano-ledger-specs/issues/563).

Instead, we can do this: 

```haskell

newtype Hash = Hash
  { unHash :: Int
  } deriving stock (Show, Generic)
    deriving newtype (Eq, Ord, Hashable)
    deriving anyclass (HasTypeReps)

```

The custom instance for BlockHeader currently refers to `typeOf Hash` (instead of `typeReps Hash`), which is why the Hash type is being correctly picked up. With a proper HasTypeReps instance, we can amend the BlockHeader instance like so:

```haskell 
instance HasTypeReps BlockHeader where
  typeReps x = typeOf x
               <| typeReps (undefined :: Hash)
               <> typeReps (x ^. bhUtxoHash :: Hash)
               <> typeReps (x ^. bhDlgHash :: Hash)
               <> typeReps (x ^. bhUpdHash :: Hash)
               <> typeReps (x ^. bhSlot :: Slot)
               <> typeReps (x ^. bhIssuer :: VKey)
               <> typeReps (x ^. bhSig :: Sig Hash)
```
