### ISSUE TITLE
Formulate and implement properties for PBFT STS in Byron-Shelley

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/cardano-ledger-specs#534]
Once `SIGCNT` is [properly tested](https://github.com/input-output-hk/cardano-ledger-specs/issues/533), the `PBFT` STS that depends on the `SIGCNT` STS can be tested. Formulate and implements properties for `PBFT`.

**Comment by dnadales** [comment]
Closing this for now. Feel free to re-open if anybody thinks this is necessary.
