### ISSUE TITLE
Add time-traveling block header validation property for Byron

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#535]
State the property that states that we can travel back in time `k` blocks and forward in time `2k` slots and validate headers using a subset of the ledger state.

A visual sketch of this property is shown below:

![image](https://user-images.githubusercontent.com/175315/58808380-318b5f80-861a-11e9-9728-c1d8ceeaf159.png)

Stating the property for some abstract function can be a first step. We can later make this function concrete by adapting the ledger and chain rules.

Related to https://github.com/input-output-hk/cardano-ledger-specs/issues/529

**Comment by dnadales** [comment]
After discussing with @nc6 it seems that we should try to formalize:

> There exists a function `f` such that, for any chain `C` and corresponding chain state `S`, given a fragment `C1={b_0, ..., b_n}` with headers `{h_0, ..., h_n}` such that the transitions `S -- b_0 --> S_0 .... S_(n-1) -- b_n --> S_n` are valid in `CHAIN`, the corresponding transitions `f S -- h_0 --> T_0 .... T_(n-1) -- b_n --> T_n` is valid in `BHEAD+PBFT`, provided that `slots C1 \subseteq [C - 2k, C+2k]`

This will require:

- Change the `DELEG` rule so that activation *does not take place there*
- Call the `ADELEG` rule from the `BHEAD` rule, so the activation of delegation takes place there

**Comment by nc6** [comment]
It's not quite `anachronisticProtocolLedgerView` - that's closer to the function `f` in forumulation 2. But close enough!
