### ISSUE TITLE
Identify which types with a HasTypeReps instance need tests

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#537]
We need to check that the the `HasTypeReps` instances are correctly defined. To this end, we need to write down tests for these instances, which means writing tests for the `typeReps` and `abstractSize` functions.

This issue is about identifying which data types in the Byron executable specs need tests, and creating separate issues to tackle this in our next iterations.

**Comment by uroboros** [comment]
this will be resolved by these issues:

* https://github.com/input-output-hk/cardano-ledger-specs/issues/563
* https://github.com/input-output-hk/cardano-ledger-specs/issues/564
