### ISSUE TITLE
Specify initial rules for `UPI` states

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#548]
To write trace generators for the different `UPIX` transition systems we need to specify the initial states of these transition system. 

Write initial rules for them. For now, we might only want to add the initial rules to the executable spec and leave the formal spec unaltered.

**Comment by mdimjasevic** [comment]
From what I can see, that's 13 UPI* STSes that need to be checked and potentially updated in case they're missing initial rules.

**Comment by mdimjasevic** [comment]
Based on an internal discussion, only these STSes need initial rules: `UPIREG`, `UPIVOTES` and `UPIEND`.
