### ISSUE TITLE
Write UPIEND trace generators

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#551]
Include also coverage tests:

- [x] Define the cases the generators have to cover
- [x] Write coverage tests for those cases
- [ ] Check that the tests pass

Some questions that arose while working on this issue:

- [x] Why are there so many blocks with empty votes?
- [x] Is it enough that around 10-20% of the proposals get confirmed?
- [x] Is it enough that around 10-20% of the confirmed proposals get scheduled for adoption?

Also note that the coverage metrics we get depend on the length of the trace and `k` value chosen: for instance, if we have a large `k` value but short traces (say `k=100` and a trace of length `100`) then no proposal will get confirmed.

**Comment by mdimjasevic** [comment]
@dnadales , can you expand on what you meant by coverage tests, please?

**Comment by dnadales** [comment]
Closed by https://github.com/input-output-hk/cardano-ledger-specs/pull/618
