### ISSUE TITLE
Test HasTypeReps instances and Size functions for Block/Header/Body types

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#563]
Write unit/property tests for the `HasTypeReps` instances for block/header/body types. Test the Size functions for these types, which are dependent on the HasTypeReps instances.

There are 2 known bugs in `bHeaderSize`. 

In `bHeaderSize`, we define "costs" for each type contained in a block header. These types need to be held consistent with those given by typeReps, e.g. if we specify SKey in costs for bHeader, then typeReps for BlockHeader should include SKey (and not Natural, as it currently does).

1) the header has a `SKey` and `Slot`, along with other data. For both the SKey and Slot `HasTypeReps` instances, we use GenNewtypeDeriving, e.g.: 

```
λ >  newtype X = X Int deriving (Generic, HasTypeReps)
λ > typeReps (X 0)

fromList [Int]
```

This means that for the `Skey/Slot` HasTypeReps instances we will only see the inner type in typeReps. To retain the newtype wrapper: 

```
λ > newtype X = X Int deriving (Generic)
λ > instance HasTypeReps X
λ > typeReps (X 0)

fromList [X,Int]
```

2) the HasTypeReps instance for `TxWits/Wit` does not match the costs specified in `bHeaderSize` (this will be fixed by https://github.com/input-output-hk/cardano-ledger-specs/issues/523)

**Comment by uroboros** [comment]
as an example, for the Slot new type, we currently have

```Haskell
newtype Slot = Slot { unSlot :: Word64 }
  deriving stock (Show)
  deriving newtype (Eq, Ord, Hashable, HasTypeReps)
```

which needs to use `deriving anyclass` for HasTypeReps:

```haskell 
newtype Slot = Slot { unSlot :: Word64 }
  deriving stock (Show, Generic)
  deriving newtype (Eq, Ord, Hashable)
  deriving anyclass (HasTypeReps)
```

**Comment by dnadales** [comment]
:ok_hand:
