### ISSUE TITLE
Hook `goblins` up to the STS instances which have HasTrace instances

### ISSUE THREAD

**Issue by mhuesch** [input-output-hk/cardano-ledger-specs#568]
## Background

For some of the STS rules, we have instances of `HasTrace`, which allow us to generate valid sequences of states and labels (signals) which transition between the states.

We want to apply the goblins genetic algorithm approach to mutating these traces, so that we can get interesting invalid sequences of labels (signals) which will trigger `PredicateFailure`s.

## Proposed Solution

Define 
```
breedStsGoblins
  :: forall sts
   . (HasTrace sts, Goblin Bool (Signal sts))
  => PredicateFailure sts
  -> IO (Population Bool)
```
which will generate traces and then mutate them with goblins, using an objective function to reward the triggering of `PredicateFailure`s.

**Comment by mhuesch** [comment]
I'm unable to update this, but it should belong to https://github.com/input-output-hk/cardano-ledger/milestone/19

**Comment by dnadales** [comment]
Is this done @mhuesch ?

**Comment by mhuesch** [comment]
Yep! Sorry, let this go stale.

**Comment by dnadales** [comment]
No problem! We have a lot to keep track of :D
