### ISSUE TITLE
What happens in `NEWEPOCH` with `Nothing` rewards update

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#577]
The `ru` rewards update is an optional value in the state of the `NEWEPOCH`
rule. It is used in the `applyRUpd` function which does take an explicit value,
not an optional. We should define what happens in the case of an empty rewards
update, unchanged `NewEpochState` or only unchanged `EpochState`.

**Comment by JaredCorduan** [comment]
We should also write a property that says "the reward update will only every be equal to `Nothing` in the `NEWEPOCH` transition **only** in the case that there were not blocks strictly between slot `( firstSlot epoch s ) + StartRewards` and slot `firstSlot ((epoch s)+1)`
