### ISSUE TITLE
Fix type of `PParams`

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#601]
Currently `PParams` is a record an it is updated using a mapping `Pgm |-> Value`. In the exec spec the record type is used whereas the formal spec uses the mapping. This would imply checking for presence in every case where a protocol parameter is read.

**Comment by JaredCorduan** [comment]
We can look to the Byron exec spec for inspiration.

**Comment by JaredCorduan** [comment]
The `Ppm |-> Value` mapping is maybe not worth keeping. I like the idea of getting rid of it all together and having the proto param updates just specify every parameter.
