### ISSUE TITLE
Add support for mutated traces

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#604]
## Background

As an example, consider the tests that check that delegation certificates cannot be replayed (which amounts to checking that in any valid trace there are no duplicated certificates). 

Currently these tests are passing, however we cannot be sure whether it is because the operational rules for delegation forbid this, or because the generators do not allow the generation of duplicated certificates. 

We do not want to generate invalid signals when composing signal generators, lest we might get very inefficient generators (where the probability of generating a valid signal decreases as we compose more signal generators). This led us to duplicate the logic of our different operational-semantics rules in the generators and in the STS rules. As a consequence, generators might be hiding errors in our operational rules (as explained above with the example of the delegation certificates).

An example of "error" hiding in the operational rules can be seen by removing the check that `(e_d, vk_s) ∉ eks` from the implementation of the `SDELEG` rule:

![image](https://user-images.githubusercontent.com/175315/60101936-f7b30200-975c-11e9-9664-83c806585f16.png)

If we do this then in principle we could generate duplicated delegation certificates in a trace. However, since the generators are generated invalid signals according to the rule above, the tests will pass with this incorrect implementation of the `SDELEG` rule.

Ideally, in the case above, we would like to see an failure in the property tests after manually injecting this error.

## Proposed Solution

We could extend the `HasTrace` type-class with two functions: `mutate`

```haskell
mutate :: Signal s -> Gen (Signal s)
```
which given a signal generates a mutated version of it, and `traceWithMutations`

```haskell
traceWithMutations
  :: Int
  -- ^ Length of the generated trace.
  -> Gen (Trace s)
```

which generates a valid trace, but mutating the generated (valid) signals with a certain probability (which might be a parameter of this function as well) so that the STS rules are fed with invalid signals as well.

Then, for example, we could replace the current version of the property that checks that delegation certificates are not replayed:

```haskell
dcertsAreNotReplayed :: Property
dcertsAreNotReplayed = withTests 300 $ property $
  forAll (trace @DBLOCK 1000) >>= dcertsAreNotReplayedInTrace
```

by this version that uses `traceWithMutations`

```haskell
dcertsAreNotReplayed :: Property
dcertsAreNotReplayed = withTests 300 $ property $
  forAll (traceWithMutations @DBLOCK 1500) >>= dcertsAreNotReplayedInTrace
```

Note that for instance in the snippet above we increased the maximum trace size since invalid signals reduce the average size of the trace.

When we do not want to generate invalid signals (for instance when composing generators), we can use the `sigGen` and `trace` functions, as we do now.

## Next steps

- [x] Discuss this with: @nc6 @ruhatch @JaredCorduan @mhuesch @mgudemann  and others who might be interested
- [x] Submit a draft PR to discuss the proposed solution. Use `dcertsAreNotReplayed` as running example.

## See also

- Issue #568.

![image](https://user-images.githubusercontent.com/175315/60103066-39dd4300-975f-11e9-84b3-3d3478429bfd.png)

**Comment by mhuesch** [comment]
> An example of "error" hiding in the operational rules can be seen by removing the check that `(e_d, vk_s) ∉ sds` from the implementation of the SDELEG rule:

Should that read `(e_d, vk_s) ∉ eks`?

**Comment by mhuesch** [comment]
In order to support `Trace`s with mutations, wouldn't we have to change https://github.com/input-output-hk/cardano-ledger-specs/blob/2addd4e68b010a1a77c05d24a2540e5947904052/byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs#L50-L61

so that it contained the resultant `PredicateFailure`s when an STS rule encountered them? I imagine that we would stop the trace once it encountered `PredicateFailure`s, so perhaps the type would look like
```
      , _traceTrans :: ![(Either [PredicateFailure s] (State s), Signal s)]
```

It would be good to talk over how this might fit with the changes I'm making for goblins.

**Comment by dnadales** [comment]
> > An example of "error" hiding in the operational rules can be seen by removing the check that `(e_d, vk_s) ∉ sds` from the implementation of the SDELEG rule:
> 
> Should that read `(e_d, vk_s) ∉ eks`?

Yes, good catch!

**Comment by dnadales** [comment]
> In order to support `Trace`s with mutations, wouldn't we have to change
> 
> https://github.com/input-output-hk/cardano-ledger-specs/blob/2addd4e68b010a1a77c05d24a2540e5947904052/byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs#L50-L61
> 
> so that it contained the resultant `PredicateFailure`s when an STS rule encountered them? I imagine that we would stop the trace once it encountered `PredicateFailure`s, so perhaps the type would look like
> 
> ```
>       , _traceTrans :: ![(Either [PredicateFailure s] (State s), Signal s)]
> ```
> 
Not in this case. If the trace generator sees a failure, then it continues trying to generate a signal. So in this issue we're talking about valid traces. 

However, for invalid trace generation we will have to add another `Trace` variant, that contain predicate failures as you mentioned.

> It would be good to talk over how this might fit with the changes I'm making for goblins.

:+1:

**Comment by dnadales** [comment]
>            , _traceTrans :: ![(Either [PredicateFailure s] (State s), Signal s)]

Also I'm thinking we might want to have this type be:

      , _traceTrans :: ![((State s, [PredicateFailure s]), Signal s)]

since even if we have a predicate failure the rules return a state.

**Comment by dnadales** [comment]
Code jamming with @nc6 and @mhuesch 

```haskell
testsuite
class STS s => HasTrace s where
  initEnvGen :: Gen (Environment s)

  sigGen :: (Maybe (PredicateFailure sts)) -> Environment s -> State s -> Gen (Signal s)
  sigGen = sigGenWithFailure Nothing 

	sigGenWithFailure :: (Maybe (PredicateFailure sts)) -> Environment s -> State s -> Gen (Signal s)
  

  trace
    :: Int
    -- ^ Maximum length of the generated traces. The actual length will be between 0 and this
    -- maximum.
    -> Gen (Trace s)
  trace n p = traceWithProfile (Maximum n) validProfile (sigGen @s)

  traceWithProfile
    :: TraceLength
    -- ^ Maximum length of the generated traces. The actual length will be between 0 and this
    -- maximum.
    -> Gen (Trace s)
  traceWithProfile n p = traceSigGen n p (sigGen @s)
  
  traceOfLength
    :: Int
    -- ^ Desired length of the generated trace. If the signal generator can generate invalid signals
    -- then the resulting trace might not have the given length.
    -> Gen (Trace s)
  traceOfLength n p = traceSigGen (Desired n) (sigGen @s)

data TraceLength = Maximum Int | Desired Int

data TraceProfile sts = TraceProfile 
	Int -- ^ Proportion of 'valid' cases to generate
  [ ( PredicateFailure sts -- Failure condition
    , Int -- Proportion of cases in which to generate this failure
    )
  ]

type PFMap = M.Map (PredicateFailure sts) (NE.List (GoblinData g)) -- maybe `Genome g`, not `GoblinData g`

{-
Steps:
1. learn by training goblins, get Genomes/GoblinData
2. package them ^ into `PFMap`
3. modify `signGenWithFailure` to use `PFMap`

-}

validProfile :: TraceProfile sts
validProfile = TraceProfile 1 []

-- Usage Example???

dcertsAreNotReplayed :: Property
dcertsAreNotReplayed = property $
  forAll (trace @DBLOCK 1000) >>= dcertsAreNotReplayedInTrace

dcertsAreNotReplayed :: Property
dcertsAreNotReplayed = property $
  forAll (traceWithProfile @DBLOCK profile 1500) >>= dcertsAreNotReplayedInTrace
  where
    profile = ???


fooBar :: Trace sts -> TraceProfile sts -> Trace sts

 
data GoblinData g = GoblinData
  { -- | Remaining genes, controlling how a goblin operates
    _genes       :: !(Genome g)
    -- | A goblin's bag of tricks contains items of many differnt types. When
    -- tinkering, a goblin (depending on its genome) might look in its bag of
    -- tricks to see whether it has anything of the appropriate type to replace
    -- what it's currently tinkering with (or, depending on the type, do
    -- something different - for example, utilise a monoid instance to add
    -- things together).
  , _bagOfTricks :: !(TypeRepMap [])
  }

type Genome g = [g]

-- `Genome Bool` is main instance used
```
