### ISSUE TITLE
One-way transfer from legacy addresses

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#640]
In order to reduce the number of legacy/bootstrap addresses, we could consider the following: only allow transfer _out_ of these addresses. This might mean allowing such transfers to have no fees.

**Comment by mgudemann** [comment]
is this resolved with the instantaneous rewards #881 ?

**Comment by JaredCorduan** [comment]
No, this is regarding a different type of Byron address. In Shelley, these will behave exactly like enterprise addresses. The idea here is to move everyone to the new Shelley addresses.

**Comment by JaredCorduan** [comment]
the real incentive to move off these is to be allowed to delegate, I do not think we need this.
