### ISSUE TITLE
Byron: Specification testing, refinement, and synchronisation :nail_care:

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#650]
This epic groups tasks related to the formal and executable specifications for Byron, which are **required** for the conformance tests.

**Comment by uroboros** [comment]
issues related to synchronising the Executable spec with the Formal one:

https://github.com/input-output-hk/cardano-ledger-specs/issues/674
https://github.com/input-output-hk/cardano-ledger-specs/issues/675
https://github.com/input-output-hk/cardano-ledger-specs/issues/676
https://github.com/input-output-hk/cardano-ledger-specs/issues/677
https://github.com/input-output-hk/cardano-ledger-specs/issues/678
https://github.com/input-output-hk/cardano-ledger-specs/issues/679
https://github.com/input-output-hk/cardano-ledger-specs/issues/680
https://github.com/input-output-hk/cardano-ledger-specs/issues/681
