### ISSUE TITLE
Byron: Validate invalid generated chains

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#652]

**Comment by mhuesch** [comment]
I am closing this now that #836 has merged.

**Comment by dnadales** [comment]
Not so fast :cowboy_hat_face: :slightly_smiling_face: We still have some opened issues. We might want to omit the predicate inclusion and STS independence checks, but I think it is sensible to check conformance of invalid headers.

![image](https://user-images.githubusercontent.com/175315/65433665-bc88a380-de1d-11e9-9b08-c8eed678ef41.png)

**Comment by dnadales** [comment]
So maybe we can close this one after #787 is completed. Makes sense?

**Comment by mhuesch** [comment]
Ah, hadn't realized those fell under this umbrella. Thanks for keeping me in ✔️ 

> So maybe we can close this one after #787 is completed. Makes sense?

Sounds good to me.
