### ISSUE TITLE
Align formal and executable specifications

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#653]
We did a lot of work intro bringing the two sets of rules in sync, but the do not fully agree at the moment. This mismatch makes planning hard since quite often, we have to fix issues in the executable specs when working on other kind of issues.

Since the formal and executable specifications were developed in parallel, we need to check that the latter conforms to the former. An initial break down of this task can be done per rule type:

- [ ] Chain rules
- [ ] Ledger rules
  - [ ] UTxO
  - [ ] Delegation
  - [ ] Update

**Comment by uroboros** [comment]
Decomposed this issue into these ones:

https://github.com/input-output-hk/cardano-ledger-specs/issues/674
https://github.com/input-output-hk/cardano-ledger-specs/issues/675
https://github.com/input-output-hk/cardano-ledger-specs/issues/676
https://github.com/input-output-hk/cardano-ledger-specs/issues/677
https://github.com/input-output-hk/cardano-ledger-specs/issues/678
https://github.com/input-output-hk/cardano-ledger-specs/issues/679
https://github.com/input-output-hk/cardano-ledger-specs/issues/680
https://github.com/input-output-hk/cardano-ledger-specs/issues/681

**Comment by uroboros** [comment]
Review complete - created detailed issues for further actions

**Comment by uroboros** [comment]
one more issues (to fix some typos in the Byron Ledger formal spec) https://github.com/input-output-hk/cardano-ledger-specs/issues/682
