### ISSUE TITLE
Relation operator (-->) hard to translate to exec spec

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#678]
In all exec. spec translations of the (--->) operator in the formal spec, the exec spec looks quite far from the formal spec. We may be able to greatly improve alignment of EXEC SPEC <-> FORMAL SPEC by devising a hakell operator for (--->)

E.g. in the exec spec for the UPV STS we have 

	inMap an av (swVer <$> avs) ?! AVChangedInPVUpdate an av (Map.lookup an avs)

The (|-->) operator is doing a lookup and let bind, so might be tricky to abstract nicely.

![Screenshot3](https://user-images.githubusercontent.com/8812/62035674-9addb800-b1f0-11e9-90c8-e82660849d68.png)

This is also the case for the UPEND Rule, see eqs (35/36/37)

**Comment by uroboros** [comment]
also see https://github.com/input-output-hk/cardano-ledger-specs/issues/745 for an example in the Shelley spec

**Comment by dnadales** [comment]
@redxaxder @uroboros should we close this as "won't fix"?

**Comment by uroboros** [comment]
👍
