### ISSUE TITLE
Shelley: Specification testing, refinement, and synchronisation

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-specs#683]

**Comment by uroboros** [comment]
Issues related to synchronising Executable spec with the formal spec:

Updates: 

* PPUP https://github.com/input-output-hk/cardano-ledger-specs/issues/729
* AVUP https://github.com/input-output-hk/cardano-ledger-specs/issues/730

UTxO:

* UTXO https://github.com/input-output-hk/cardano-ledger-specs/issues/731
* UTXOW https://github.com/input-output-hk/cardano-ledger-specs/issues/732

Delegation:

* DELEG https://github.com/input-output-hk/cardano-ledger-specs/issues/733
* POOL https://github.com/input-output-hk/cardano-ledger-specs/issues/734
* DELEGS https://github.com/input-output-hk/cardano-ledger-specs/issues/735

Ledger State:

* LEDGER https://github.com/input-output-hk/cardano-ledger-specs/issues/736

Rewards/epoch boundary: 

* SNAP https://github.com/input-output-hk/cardano-ledger-specs/issues/737
* NEWPP https://github.com/input-output-hk/cardano-ledger-specs/issues/738
* EPOCH https://github.com/input-output-hk/cardano-ledger-specs/issues/739

Blockchain layer:

* UPDN https://github.com/input-output-hk/cardano-ledger-specs/issues/740
* NEWEPOCH https://github.com/input-output-hk/cardano-ledger-specs/issues/741
* RUPD https://github.com/input-output-hk/cardano-ledger-specs/issues/742
* BHEAD https://github.com/input-output-hk/cardano-ledger-specs/issues/743
* OCERT https://github.com/input-output-hk/cardano-ledger-specs/issues/744
* OVERLAY https://github.com/input-output-hk/cardano-ledger-specs/issues/745
* PRTCL https://github.com/input-output-hk/cardano-ledger-specs/issues/746
* BBODY https://github.com/input-output-hk/cardano-ledger-specs/issues/747
* CHAIN https://github.com/input-output-hk/cardano-ledger-specs/issues/748

**Comment by uroboros** [comment]
an issue for some typos found in Shelley Formal Spec -> https://github.com/input-output-hk/cardano-ledger-specs/issues/749
