### ISSUE TITLE
Agree on approach for conformance testing of invalid chains

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#711]
As a first step towards conformance testing of invalid chains (#652) we should agree on what approach are we going to take.

Draft up some proposals and discuss this among the involved parties: @ruhatch @nc6 @mhuesch @dnadales .

**Comment by dnadales** [comment]
# Proposal: invalid last signal<a id="sec-1" name="sec-1"></a>

-   Generate a valid trace
-   Append an invalid signal

We might need a new type of traces:

```haskell
module Trace.Invalid  where

import qualified Trace as Trace

data Trace s = Trace s
  { prefix :: Trace.Trace s
  , sig :: Signal s
  -- ^ Last signal in the trace. This might cause a predicate failure, but it
  -- isn't guaranteed to do so, since invalid trace generation is
  -- probabilistic.
  , errorOrlastState :: Either (PredicateFailure s) (State s)
  }

invalidTrace :: STS s => TraceProfile -> Gen (Trace s)
invalidTrace profile = do
  tr <- Trace.trace @CHAIN
  let env = traceEnv tr
      st = lastState tr
  iSig <- sigGenWithProfile profile env st
  est' = applySTS @s TRC(env, st, iSig)
  pure $! Trace { prefix = tr
                , sig = iSig
                , errorOrlastState = st'
                }
```                

## Questions<a id="sec-1-1" name="sec-1-1"></a>

### Do we need conformance tests for each kind of failures?<a id="sec-1-1-2" name="sec-1-1-2"></a>

This is:
-   invalid chains tests for Delegation
-   invalid chains tests for Update
-   invalid chains tests for UTxO

Or do we want a single conformance test that can originate all sorts
of predicate failures?

The advantage of the first approach is that we have a smaller state
space to explore in each test. The advantage of the second approach
is that we can test the effect of failures interaction.

### How would the conformance tests look like?<a id="sec-1-1-3" name="sec-1-1-3"></a>


```haskell
invalidTrace @CHAIN profile
res = foldM elaborateAndUpdate  concreteState (prefix tr)
evalEither res -- So here we make sure that all but the last signals can be
               -- successfully applied
res' = elabodataAndUpdate (state res) (lastSignal tr) -- here we're assuming
                                                      -- the last state of the
                                                      -- trace contains an
                                                      -- invalid signal
case (res', errorOrlastState tr) of
  (Right _, Right _) ->
    pass -- It could be that the invalid signals generator did not produce an
         -- invalid signal (since it is probabilistic).
  (Left concreteError, Left abstractError)
    undefined concreteError abstractError -- Do we need to map concrete and
                                          -- abstract errors?
  (_, _) ->
    fail misserably -- A mismatch in the success status of the abstract and
                    -- concrete models is a failure.
```

In the code above, what is the `profile` that we want?

**Comment by mhuesch** [comment]
In the "Do we need conformance tests for each kind of failures?" section, it seems to me that we definitely want to test interactions between parts of the system. We could optionally also test sub-parts ("sub STSs"), because the state space would be smaller and the tests would go faster. Certainly, training goblins for those sub-parts is easier.

**Comment by nc6** [comment]
In terms of the system interactions, I think we might be able to get away with only testing subsystems, provided we also have some property testing of the "future independence" property I alluded to the other day; which is to say, we have a window within which it should be guaranteed that changes to delegation/update/UTxO do not affect the others. Then conformance tests could attempt to verify this (elaborate into a block containing just the delegation/UTxO/update payload, and check that the other bits of the system don't change).

It's possible that there could be complex interactions, but my intuition is that these are unlikely.

**Comment by mhuesch** [comment]
Agree - if we have an independence property, it would simplify things to just test subsystems. I have some concern that for large `Signal` datatypes, it is difficult to tinker with things and trigger *just one* `PredicateFailure`. Many could be triggered, and then establishing an equivalence between model and implementation might become difficult.

**Comment by dnadales** [comment]
Closed by https://github.com/input-output-hk/cardano-ledger/pull/608
