### ISSUE TITLE
Sync executable with formal spec - AVUP STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#730]
<img width="873" alt="Screenshot_FIG10" src="https://user-images.githubusercontent.com/8812/62696415-a7c08f80-b9d8-11e9-9393-65b182781648.png">

The helper function `newAV` is not fully implemented in the exec. spec:

	newAVs :: Applications -> Map.Map Slot Applications -> Applications
	newAVs avs favs = if not $ Map.null favs
	  then let maxSlot = maximum $ Map.keys favs in favs Map.! maxSlot
	  else avs

* does not deal check `validAV`
* does not do Union override of `avs` and `avs'`
* in general, does not resemble formal spec clearly

<img width="873" alt="Screenshot_FIG12" src="https://user-images.githubusercontent.com/8812/62696446-ba3ac900-b9d8-11e9-98be-716cbc9bf7ac.png">

* the exec. spec does not do a Union override in the two cases highlighted
* does resemble the formal spec closely

**Comment by mgudemann** [comment]
We often use `Map.union new old` for union override, as it is left overriding. Does `Relation` provide a union override operator ?

**Comment by uroboros** [comment]
yes, there's an unicode approximation in the Relation class

     (∪) :: (Ord (Domain m), Ord (Range m)) => m -> m -> m
     (⨃) :: (Ord (Domain m), Ord (Range m), Foldable f) => m -> f (Domain m, Range m) -> m

**Comment by JaredCorduan** [comment]
Note that the picture in this Issue is from an outdated version of the formal spec. The `newAVs` method is now called in the `LEDGERS` transition instead (and moving app versions from `favs` to `avs`, etc).
