### ISSUE TITLE
Sync executable with formal spec - UTXOW STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#732]
<img width="873" alt="Screenshot_FIG22" src="https://user-images.githubusercontent.com/8812/62696831-8d3ae600-b9d9-11e9-84c9-a06af7d02dfd.png">

The formal spec checks for equality between `witsNeeded` and "witnessed keys", while the exec spec checks for `isSubsetOf`:

	let witnessKeys = Set.map (\(WitVKey vk _) -> hashKey vk) wits
	let needed = witsVKeyNeeded (_utxo u) tx _dms
	needed `Set.isSubsetOf` witnessKeys  ?! MissingVKeyWitnessesUTXOW

**Comment by mgudemann** [comment]
this is due to the exec spec already supporting multi-sig, the formal spec will be changed in the multi-sig merge

**Comment by uroboros** [comment]
ok, I'll close
