### ISSUE TITLE
Sync executable with formal spec - SNAP STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#737]
<img width="985" alt="Screenshot_FIG38" src="https://user-images.githubusercontent.com/8812/62697951-34208180-b9dc-11e9-9ddf-79b6ef3455f7.png">

* the helper function `aggregate` is not explicitly expressed in the exec. spec, although there is a related `consolidate` function, but this is not used widely (and instead the aggregation often happens implicitly)
* also, the `stakeRelation` calculation is quite indirectly expresseed in the exec. spec.

<img width="987" alt="Screenshot_FIG40" src="https://user-images.githubusercontent.com/8812/62697993-52867d00-b9dc-11e9-9622-d9c9aa92fd02.png">

In the Exec. spec, the environment for this STS does not have `blocks`.

**Comment by JaredCorduan** [comment]
`blocks`has been removed from `SNAP` in the formal spec.
