### ISSUE TITLE
Sync executable with formal spec - NEWPP STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#738]
<img width="870" alt="Screenshot_FIG44" src="https://user-images.githubusercontent.com/8812/62698216-e0626800-b9dc-11e9-94ee-a4cc34fbd4e6.png">

* in the formal spec in FIG 50 (Eqs 25, 26), in the formula for `oblg_new`, the spec uses in effect `firstSlot`, while in the exec spec we use `slotFromEpoch e`.

**Comment by mgudemann** [comment]
I think we return the `clearPup utxoSt` ?

**Comment by uroboros** [comment]
> I think we return the `clearPup utxoSt` ?

you're right (I see now was reviewing a slightly stale NewPP)
