### ISSUE TITLE
Sync executable with formal spec - EPOCH STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#739]
<img width="847" alt="Screenshot_FIG46" src="https://user-images.githubusercontent.com/8812/62698316-23244000-b9dd-11e9-9ae5-f27b50be937c.png">

* In the Exec. spec, the environment for this STS does not have `blocks`
* also, `votedValue_PParams` is not being used yet in the exec. spec to compute `pp_new`

**Comment by JaredCorduan** [comment]
`votedValue_PParams` was implemented in https://github.com/input-output-hk/cardano-ledger-specs/pull/714 

`blocks` was removed from the environment of `EPOCH` in the formal spec some time recently as well.
