### ISSUE TITLE
Sync executable with formal spec - NEWEPOCH STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#741]
<img width="834" alt="Screenshot_FIG55" src="https://user-images.githubusercontent.com/8812/62701622-1277c800-b9e5-11e9-9e0a-8249a33cebf8.png">

The exec. spec effectively does 

	floor (activeSlotCoeeff pp * (floor ((d pp) * SlotsPerEpoch))) - 1
	
instead of the formal spec's

	floor (activeSlotCoeeff pp * ((d pp) * SlotsPerEpoch)))

<img width="871" alt="Screenshot_FIG56" src="https://user-images.githubusercontent.com/8812/62701741-55d23680-b9e5-11e9-8064-a5cfec3e0ae8.png">

*  the exec spec considers the two cases

	e_l + 1 /= e
	e_l + 1 == e

and the formal spec uses two different cases althogether

	e  = e_l + 1
	e_l /= e + 1

* the `sd` and `pd'` definitions in the formal spec are hard to recognise in the exec spec

**Comment by mgudemann** [comment]
I see ```if eL' + 1 /= e'
    then pure src
    else do``` in the exec spec

**Comment by mgudemann** [comment]
I agree that `aggregate+` should be translated more clearly, maybe using `Relation` could be of help here?

**Comment by uroboros** [comment]
> I see `if eL' + 1 /= e' then pure src else do` in the exec spec

thanks, fixed that in the above (but the mismatch remains)
