### ISSUE TITLE
Sync executable with formal spec - BHEAD STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#743]
<img width="864" alt="Screenshot_FIG62" src="https://user-images.githubusercontent.com/8812/62702727-d72ac880-b9e7-11e9-9fee-f8697d2a4da4.png">

It's not clear that the exec. spec code 

	nes'' = nes' { nesRu = ru' }

is achieving the Union override in Eq (35).

**Comment by mgudemann** [comment]
I think this some abuse of notation, `nes'` is a `NewepochState` and has a `Maybe RewardUpdate` record field

**Comment by uroboros** [comment]
ah ok, let's make a note in the code to clarify the seeming discrepancy

**Comment by JaredCorduan** [comment]
yep, it's overloaded notation, treating records like maps
