### ISSUE TITLE
Sync executable with formal spec - OCERT STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#744]
<img width="868" alt="Screenshot_FIG64" src="https://user-images.githubusercontent.com/8812/62702826-19eca080-b9e8-11e9-832f-27667cc139a8.png">

* the exec. spec uses `tau` in `verify vk_cold` instead of `sigma`. Similarly, the 
the exec. spec uses `sigma` in `verify vk_hot` instead of `tau`:

	verify vk_cold (vk_hot, n, c0) tau ?! InvalidSignatureOCERT
	verifyKES vk_hot bhb sigma t ?! InvalidKesSignatureOCERT

* the formal spec uses Union override, and in the exec. spec we do:

	Map.insert hk n cs

**Comment by mgudemann** [comment]
first point, good catch!
2nd point, this is probably a premature optimization as we know there's only a single element begin added. Can this be handled in a nicer way using `Relation` ?

**Comment by JaredCorduan** [comment]
yes, good catch! the formal spec has tau and sigma switched (the exec spec is correct).

I'm happy either way how implement union override on a single element, ie `Map.insert hk n cs` or the more general way.
