### ISSUE TITLE
Sync executable with formal spec - OVERLAY STS

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#745]
<img width="861" alt="Screenshot_FIG66" src="https://user-images.githubusercontent.com/8812/62702933-53bda700-b9e8-11e9-9b8a-a799af56a925.png">

In the formal spec, nested lookups are very concise, but the (->) is not being translated well in the exec spec.

![Screenshot_FIG66_code](https://user-images.githubusercontent.com/8812/62703232-03931480-b9e9-11e9-8183-badd079bc23d.png)

**Comment by mgudemann** [comment]
how would you suggest to refactor this lookup?

**Comment by uroboros** [comment]
something like the oh-noes operator could work

    (?!) :: Bool -> PredicateFailure sts -> Rule sts ctx ()

e.g.
    (|-->) :: Relation r => (Range r) -> PredicateFailure sts -> Rule sts ctx (Domain r)

(which fails with a predicate failure if there's no corresponding key)
