### ISSUE TITLE
Bleeding Italics

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#775]
* I see these italic bleeds quite often, can we find them all with a pattern match on the latex?
* also some typos

<img width="884" alt="Screenshot 2019-08-20 at 13 38 21" src="https://user-images.githubusercontent.com/8812/63344379-9b312500-c350-11e9-9a49-79f5518ca4b0.png">

**Comment by JaredCorduan** [comment]
yes indeed we can let the robots turn `\em{foo}` into `{\em foo}` for us! thanks!

**Comment by JaredCorduan** [comment]
or better yet, we can turn `\em{foo}` into `\emph{foo}`!
