### ISSUE TITLE
Fragmentation of Information

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-ledger-specs#851]
I am noticing that important information is scattered in various places (design documents, spec, papers).  I will think about how this can best be organised for ease of reference.

**Comment by JaredCorduan** [comment]
Keeping all the documents well organized is a great priority! Let's makes sure that the [readme](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/README.md) stays in sync with whatever we do (the beginning of the readme does list off the most important documents).
