### ISSUE TITLE
Vanish `Natural`'s from the specs

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/cardano-ledger-specs#861]
The `-` operation on naturals can cause an `arithmetic underflow` exception, which cannot be traced, all we are left with is an error message like the following one:

```
  Test.Cardano.Chain.Block.Model
    ts_prop_generatedChainsAreValidated:              FAIL
      Exception: arithmetic underflow
```

The Byron tests trigger this error very sporadically, and Shelley tests might have this problem as well. 

We should remove the use of `Natural`. As an alternative we could define `Natural` as a `newtype` wrapper around `Word64`, and use a custom `-` operation which also errors on underflow but with a `HasCallStack` constraint .

There might be better alternatives, so please join the discussion :point_down: if you have them.

**Comment by kevinhammond** [comment]
Hi Damian

I believe the better solution is to ban subtraction in favour of a symmetric difference operator.
Almost all (all?) uses of subtraction in the ledger are dividing a value into two smaller parts.
I've suggested to Jared et al how to do this for Shelley.  This should simplify many of the consistency proofs,  and improve concurrency (not sure whether that is an issue yet).  You really don't want the pots, slots etc. to move into negative values - this could introduce security vulnerabilities.
If you're getting underflows for these values, it would suggest a possible logic flaw.

It may be too late to do this for Byron, though I'd expect changes to be fairly localised.

**Comment by dnadales** [comment]
Ok, so after our off-github discussion, it seems that at least for Byron we want to go with a custom difference operator that gives an error with call stack.

**Comment by kevinhammond** [comment]
You shouldn’t need most error checks with a difference operator (except for major consistency/validation purposes). I’ll chat to Jared later.

**Comment by JaredCorduan** [comment]
The types of concern in Shelley :shell: are `Coin`, `Slot`, and `Epoch`.

`Coin` is an `Integer`. The other two are implemented as `SlotNo` and `EpochNo`, taken from Cardano.Slotting.Slot in cardano-base. We use a a symmetric difference operator on them.

**Comment by JaredCorduan** [comment]
I think that the nats that are left in the Shelley ledger are fine, ie things we do not use subtraction on, such as protocol versions.
