### ISSUE TITLE
remove redundant checks?

### ISSUE THREAD

**Issue by JaredCorduan** [input-output-hk/cardano-ledger-specs#864]
The consensus layer performs some checks on the block header which are also checked in the ledger layer. Should we remove this redundancy or keep it?

**Comment by dnadales** [comment]
@edsko @nc6 any thoughts on this? It seems to me avoiding redundant checks would be preferable. If so, how can we do this?

**Comment by edsko** [comment]
This is mostly a question for @nc6 I think.

**Comment by kevinhammond** [comment]
I’d be inclined to keep them in unless there’s a known performance issue?

**Comment by dnadales** [comment]
> I’d be inclined to keep them in unless there’s a known performance issue?

Any reason for doing this? 

Alternatively the ledger layer, thought the executable spec, could expose the validation functions to the consensus layer. But I don't know how easy it is to do this.

**Comment by kevinhammond** [comment]
Sent from my iPhone

> On 18 Sep 2019, at 16:37, Damian Nadales <notifications@github.com> wrote:
> 
> I’d be inclined to keep them in unless there’s a known performance issue?
> 
> Any reason for doing this?
> 
Not on the critical path. You may accidentally remove a check that is needed. Takes some human time.
Might be possible to automate. Might be possible to combine at a coarser granularity. Might even be more efficient to repeat the check. :)

**Comment by JaredCorduan** [comment]
the consensus layer does not call the `CHAIN` rule directly, so in fact we are not doing the header checks twice.
