### ISSUE TITLE
Generate _multiple_ utxo outputs to serve as inputs in `genTx`

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#877]
We are currently generating only a single input and output in `genTx`.

We need to generate a variable number of inputs and outputs (see `pickSpendingInputs` and `genRecipients` in `test\Generator\Utxo.hs`).

Once this is done, we should extend the Tx QuickCheck shrinker to shrink Outputs as well (the Tx amounts and witnesses will have to be adjusted)

**Comment by mgudemann** [comment]
generation of multiple TxOuts in Tx (including script outputs) #1118
