### ISSUE TITLE
Replace and remove pre-STS property tests and generators

### ISSUE THREAD

**Issue by uroboros** [input-output-hk/cardano-ledger-specs#880]
There are pre-STS property tests (see `shelley/tests/PropertyTests.hs`) that need to be translated as properties based on STS trace generators.

We also need to replace/remove the corresponding pre-STS generators in `test/Generator.hs`.

NOTE: This issue should be done at the end of the "Valid Generators for Known Properties" milestone.

**Comment by JaredCorduan** [comment]
I removed this from milestone S6 since the tests are actually in much better shape than I thought. Having them in the trace generation would be nice, but there are many more important things to do right now.

**Comment by JaredCorduan** [comment]
note that these now have a different name (Non-Trace) and live here: https://github.com/input-output-hk/cardano-ledger-specs/tree/master/shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/NonTraceProperties
