### ISSUE TITLE
Valid ledger state description is only in terms of the DELEG rule

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/cardano-ledger-specs#917]
The Definition 15.1 (Valid Ledger State) gives a valid ledger state only in terms of a sequence of LEDGER rule applications. The EPOCH rule also changes the ledger state - is this something that needs to be addressed?

This would mean a valid Epoch state also should be defined, and allow for defining a property stating that "the EPOCH transition is always invoked at the epoch boundary (is never blocked)".

**Comment by JaredCorduan** [comment]
duplicate of #840
