### ISSUE TITLE
Plan for shrinking

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/cardano-ledger-specs#940]
@uroboros reported that there are often issues with efficiency of shrinking.
I understand these are related to #938, #708, #684 (epic).

He suggested that I read Edsko's post https://www.well-typed.com/blog/2019/05/integrated-shrinking/, and we organize meeting with @dnadales @uroboros @mgajda @kevinhammond @mhuesch on what are the current problems, and how to best address them.

**Comment by JaredCorduan** [comment]
Closing and combining with #938
