### ISSUE TITLE
Update proofs after MIR changes

### ISSUE THREAD

**Issue by mgudemann** [input-output-hk/cardano-ledger-specs#997]
The proofs have to be updated now, as the IR certificate handling has changed. In particular, we do not force register any stake credentials any more. Instead, we drop any instantaneous rewards at the reward update application if the corresponding stake credentials are not registered at that time.

**Comment by JaredCorduan** [comment]
the proofs are: 15.1 Preservation of Value, and 15.2 Non-negative Deposit Pot
